import assert from 'node:assert/strict';
import {removeSyncedData,localUsage,syncedDataRemoval} from '../public/assets/js/account-data.js';
const state={favorites:[{id:'cloud'},{id:'local'}],backgrounds:[{id:'cloud',size:50},{id:'local',localOnly:true,size:100}],settings:{theme:'dark',local:true},syncOwnership:{userId:1,collections:{favorites:['cloud'],backgrounds:['cloud','local']},settings:['theme']},syncStatus:{lastSync:'2026-09-29T00:00:00Z'}};
const result=removeSyncedData(state,'1');
assert.deepEqual(result.favorites,[{id:'local'}]);
assert.deepEqual(result.backgrounds,[{id:'local',localOnly:true,size:100}]);
assert.deepEqual(result.settings,{local:true});
assert.equal(result.syncOwnership,undefined);
assert.equal(result.syncStatus,undefined);
assert.equal(state.favorites.length,2);
assert.equal(removeSyncedData(state,2),state);
assert.equal(removeSyncedData({favorites:[{id:'local'}]},1).favorites.length,1);
assert.equal(localUsage(state).backgroundBytes,150);
assert.equal(localUsage(state).lastSync,'2026-09-29T00:00:00Z');
assert.ok(localUsage({name:'日本語'}).bytes>JSON.stringify({name:'日本語'}).length);
const privateProviders={'providers-web':[{id:'cloud'}],'providers-ai':[{id:'private-ai'},{id:'local-ai'}],syncOwnership:{userId:1,collections:{'providers-web':['cloud'],'providers-ai':['private-ai']}}};
const providerCleanup=removeSyncedData(privateProviders,1);
assert.equal(Object.hasOwn(providerCleanup,'providers-web'),false,'no empty override may suppress the public search defaults after logout');
assert.deepEqual(providerCleanup['providers-ai'],[{id:'local-ai'}],'unowned local providers remain available');
assert.equal(syncedDataRemoval(privateProviders,1).values['providers-web'],null,'the persisted override is cleared so consumers use public defaults');
assert.equal(removeSyncedData(privateProviders,2),privateProviders,'another account cannot clear the provider overrides');
const media={backgrounds:[{id:'owned',fileId:'owned',cloudOwner:'1',cloudSync:true,fileSize:15},{id:'off',fileId:'off',cloudSync:false,fileSize:20},{id:'other',fileId:'other',cloudOwner:'2',cloudSync:true,fileSize:30},{id:'unowned',fileId:'unowned',fileSize:40}],backgroundOwnership:{userId:'1',ids:['owned','off','other']},backgroundCheckpoint:{userId:'1',document:{}},syncOwnership:{userId:'2',settings:['theme']},settings:{theme:'dark'}};
const removal=syncedDataRemoval(media,'1');assert.deepEqual(removal.values.backgrounds.map(row=>row.id),['off','other','unowned']);assert.deepEqual(removal.files,[{id:'owned',blob:null}]);assert.equal(removal.values.backgroundOwnership,null);assert.equal(removal.values.backgroundCheckpoint,null);assert.equal(removal.values.syncOwnership.userId,'2');assert.equal(removal.values.settings.theme,'dark');
assert.equal(localUsage(media).backgroundBytes,105);assert.equal(localUsage(media).bytes,localUsage(media).metadataBytes+105);
assert.deepEqual(syncedDataRemoval(media,'3').files,[]);
const pendingKey='_bg_upload_'+'a'.repeat(64),pendingState={backgrounds:[],backgroundUploadIntents:{'1':{fileKey:pendingKey,fileSize:8},'2':{fileKey:'_bg_upload_'+'b'.repeat(64),fileSize:10}}};
const pendingClean=syncedDataRemoval(pendingState,'1');assert.equal(pendingClean.values.backgroundUploadIntents['1'],undefined);assert.equal(pendingClean.values.backgroundUploadIntents['2'].fileSize,10);assert.deepEqual(pendingClean.files,[{id:pendingKey,blob:null}]);assert.equal(localUsage(pendingState).backgroundBytes,18);
console.log('Account cleanup preserves local records, removes acknowledged caches and restores public provider fallback.');
