import assert from 'node:assert/strict';
import {solarTimes,daytime,themePalette,palettes,fontUrl,fontName,color,bounded,greetingKey,searchStyles,animationLevel} from '../public/assets/js/appearance-core.js';
const equinox=new Date('2026-03-20T12:00:00Z'),equator=solarTimes(equinox,0,0);
assert.ok(Math.abs(new Date(equator.sunrise).getUTCHours()-6)<=1);assert.ok(Math.abs(new Date(equator.sunset).getUTCHours()-18)<=1);
assert.equal(daytime(new Date('2026-03-20T03:00:00Z'),35.7,139.7),true);
assert.equal(daytime(new Date('2026-03-20T15:00:00Z'),35.7,139.7),false);
assert.equal(daytime(new Date('2026-03-20T22:00:00Z'),-37,175),true);
assert.equal(daytime(new Date('2026-03-20T10:00:00Z'),-37,175),false);
assert.equal(solarTimes(new Date('2026-06-21T12:00:00Z'),89,0).polar,'day');
assert.equal(solarTimes(new Date('2026-12-21T12:00:00Z'),89,0).polar,'night');
assert.equal(solarTimes(equinox,100,0),null);
assert.deepEqual(themePalette({theme:'os'},equinox,true),palettes.dark);
assert.deepEqual(themePalette({},equinox,false),palettes.light);
assert.deepEqual(themePalette({theme:'solar',themeRegion:{latitude:0,longitude:0}},equinox,true),palettes.light);
assert.equal(themePalette({theme:'custom',customThemeId:'one',customThemes:{one:{accent:'#123456',text:'url(javascript:evil)'}}}).accent,'#123456');
assert.equal(themePalette({theme:'custom',customThemeId:'one',customThemes:{one:{text:'url(javascript:evil)'}}}).text,palettes.light.text);
assert.equal(fontUrl('javascript:alert(1)'),null);assert.equal(fontUrl('https://user:pass@example.test/font.woff2'),null);
assert.equal(fontUrl('https://example.test/font.woff2'),'https://example.test/font.woff2');
assert.equal(fontName('Noto Sans'), 'Noto Sans');assert.equal(fontName('bad;}'),null);
assert.equal(color('#123abc','fallback'),'#123abc');assert.equal(color('red','fallback'),'fallback');
assert.equal(bounded('999',16,10,32),32);assert.equal(bounded('',16,10,32),16);
assert.equal(greetingKey(8),'greeting_morning');assert.equal(greetingKey(13),'greeting_day');assert.equal(greetingKey(22),'greeting_evening');
const defaults=searchStyles({},palettes.dark);
assert.equal(defaults['--search-background'],'rgba(27,37,52,0.7)');
assert.equal(defaults['--search-width'],'900px');
assert.equal(defaults['--search-height'],'56px');
assert.equal(defaults['--search-text'],palettes.dark.text);
const design=searchStyles({searchWidthMode:'fixed',searchWidth:1200,searchHeight:'large',searchPosition:'lower',searchOpacity:2,searchBlur:-5,searchShadow:false,searchText:'url(evil)',searchBackground:'#123456'},palettes.light);
assert.equal(design['--search-width'],'900px');assert.equal(design['--search-height'],'72px');assert.equal(design['--search-offset'],'30vh');
assert.equal(design['--search-background'],'rgba(18,52,86,1)');assert.equal(design['--search-blur'],'0px');
assert.equal(design['--search-shadow'],'none');assert.equal(design['--search-text'],palettes.light.text);
assert.equal(animationLevel('rich',true),'none');assert.equal(animationLevel('low'),'low');assert.equal(animationLevel('bad'),'rich');
assert.equal(daytime(new Date(equator.sunrise),0,0),true);assert.equal(daytime(new Date(equator.sunset),0,0),false);
console.log('42 appearance core assertions passed.');
