import assert from 'node:assert/strict';
import {mediaUrl,normalizeBackground,conditionMatches,ruleScore,selectBackground} from '../public/assets/js/background-core.js';
assert.equal(mediaUrl('javascript:alert(1)'),null);assert.equal(mediaUrl('//evil.test/a'),null);assert.equal(mediaUrl('https://user:pass@test.example/a'),null);assert.equal(mediaUrl('/assets/icons/search.svg'),'/assets/icons/search.svg');
assert.equal(mediaUrl('https://example.test/a.mp4'),'https://example.test/a.mp4');
assert.equal(normalizeBackground({id:'bad',name:'Bad',type:'image',url:'javascript:1'}),null);
const row=normalizeBackground({id:'one',name:' One ',type:'gradient',blur:99,color:'url(evil)',speed:99});
assert.equal(row.name,'One');assert.equal(row.blur,40);assert.equal(row.color,'#101723');assert.equal(row.speed,4);assert.equal(row.localOnly,true);
const context={now:new Date(2026,9,2,23,30),width:390,height:844,device:'mobile',loggedIn:false,temperature:15,weather:'rain',random:()=>.1};
const check=(condition,expected=true)=>assert.equal(conditionMatches(condition,context),expected);
check({type:'time',start:'22:00',end:'06:00'});check({type:'time',start:'08:00',end:'18:00'},false);check({type:'time',start:'00:00',end:'00:00'});check({type:'time',start:'99:00',end:'06:00'},false);
assert.equal(conditionMatches({type:'time',start:'22:00',end:'06:00'},{...context,now:new Date(2026,9,2,12)}),false);
check({type:'day',days:[5]});check({type:'date',date:'2026-10-02'});check({type:'period',start:'2026-10-01',end:'2026-10-03'});
check({type:'weather',values:['rain']});check({type:'temperature',min:10,max:20});check({type:'temperature',min:20,max:30},false);
check({type:'season',value:'autumn'});assert.equal(conditionMatches({type:'season',value:'spring'},{...context,latitude:-20}),true);
check({type:'random',chance:.2});check({type:'login',value:false});check({type:'device',value:'mobile'});check({type:'screen',minWidth:300,maxWidth:500,maxHeight:900});check({type:'weather',values:['clear']},false);
assert.equal(conditionMatches({type:'weather',values:['rain']},{now:context.now}),false);
const time={type:'time',start:'22:00',end:'06:00'},mobile={type:'device',value:'mobile'},rain={type:'weather',values:['rain']};
assert.equal(ruleScore({operator:'and',conditions:[time,mobile]},context),2);
assert.equal(ruleScore({operator:'or',conditions:[{type:'login',value:true},{operator:'and',conditions:[mobile,rain]}]},context),2);
assert.equal(ruleScore({operator:'and',conditions:[time,{type:'login',value:true}]},context),-1);
assert.equal(ruleScore({operator:'or',conditions:[]},context),-1);
const items=[{id:'one',name:'One',type:'solid',rule:time},{id:'two',name:'Two',type:'solid',rule:{operator:'and',conditions:[time,mobile]}}];
assert.equal(selectBackground(items,{backgroundSwitch:'rules'},context).id,'two');
assert.equal(selectBackground(items,{backgroundSelected:'two'},context).id,'two');assert.equal(selectBackground(items,{backgroundSwitch:'random'},context).id,'one');
assert.equal(selectBackground([...items,{...items[1],id:'three'}],{backgroundSwitch:'rules'},{...context,random:()=>.9}).id,'three');
assert.equal(selectBackground([],{},context),null);
assert.equal(selectBackground([{...items[0],deleted:true},items[1]],{backgroundSelected:'one'},context).id,'two');
assert.equal(selectBackground(items.map(item=>({...item,deleted:true})),{},context),null);
console.log('41 background assertions passed.');
