import assert from 'node:assert/strict';
import {backgroundAcknowledgement as plan} from '../public/assets/js/background-sync-ack.js';
import {backgroundRecord} from '../public/assets/js/background-sync-core.js';
const revision='a'.repeat(64),blob=new Blob(['compressed'],{type:'image/png'});
const local={id:'a',name:'Local',type:'image',sourceType:'upload',fileId:'a',fileVersion:1,fileSize:20,url:'',cloudSync:true,localOnly:false};
const before=backgroundRecord(local),target=before,acknowledged={...local,fileId:undefined,fileRevision:revision,fileSize:blob.size,url:'/api/backgrounds/a/file',version:1};
const options={userId:'1',before,target,acknowledged,blob};
let result=plan({backgrounds:[local]},options);
assert.equal(result.files[0].blob,blob);assert.equal(result.values.backgrounds[0].syncedFileVersion,1);assert.equal(result.values.backgrounds[0].fileRevision,revision);assert.equal(result.values.backgrounds[0].fileSize,blob.size);
assert.equal(result.values.backgroundCheckpoint.document.a.source[0].revision,revision);assert.deepEqual(result.values.backgroundOwnership.ids,['a']);
result=plan({backgrounds:[{...local,name:'Edited during upload'}]},options);assert.equal(result.values.backgrounds[0].name,'Edited during upload');assert.equal(result.files.length,1);
const replaced={...local,fileVersion:2,fileSize:40};result=plan({backgrounds:[replaced]},options);
assert.equal(result.files.length,0);assert.equal(result.values.backgrounds[0].fileVersion,2);assert.equal(result.values.backgrounds[0].fileSize,40);assert.equal(result.values.backgrounds[0].syncedFileVersion,1);assert.equal(backgroundRecord(result.values.backgrounds[0]).source[0].revision,'local:a:2');
result=plan({backgrounds:[]},options);assert.deepEqual(result.values.backgrounds,[]);assert.deepEqual(result.files,[]);
result=plan({backgrounds:[{...local,deleted:true}]},options);assert.equal(result.values.backgrounds[0].deleted,true);
result=plan({backgrounds:[{...local,deleted:true}]},{...options,blob:null});assert.equal(result.files.length,0);assert.equal(result.values.backgrounds[0].fileId,'a');assert.equal(result.values.backgrounds[0].fileSize,local.fileSize);
result=plan({backgrounds:[{...local,cloudSync:false}]},options);assert.equal(result.values.backgrounds[0].localOnly,true);
assert.throws(()=>plan({backgrounds:[{...local,cloudOwner:'2'}]},options),/OWNER_CHANGED/);
assert.throws(()=>plan({backgrounds:[{...local,cloudSync:false}]},{...options,before:null}),/LOCAL_COLLISION/);
assert.throws(()=>plan({backgrounds:[local]},{...options,blob:new Blob(['wrong'])}),/SIZE_INVALID/);
assert.throws(()=>plan({backgrounds:[local]},{...options,blob:null}),/FILE_MISSING/);
const imported=plan({backgrounds:[],backgroundOwnership:{userId:'1',ids:['other']}},{...options,before:null,target:backgroundRecord(acknowledged,true)});
assert.equal(imported.values.backgrounds[0].fileId,'a');assert.equal(imported.values.backgrounds[0].cloudOwner,'1');assert.deepEqual(imported.values.backgroundOwnership.ids,['other','a']);
const cached=imported.values.backgrounds[0];result=plan({backgrounds:[cached]},{...options,before:backgroundRecord(cached),target:backgroundRecord(cached),blob:null});assert.deepEqual(result.files,[]);
const url={id:'a',name:'URL',type:'image',sourceType:'url',url:'https://example.test/a.png',cloudSync:true,version:2};
result=plan({backgrounds:[cached]},{userId:'1',before:backgroundRecord(cached),target:backgroundRecord(url,true),acknowledged:url});assert.equal(result.files[0].blob,null);assert.equal(result.values.backgrounds[0].fileId,undefined);assert.equal(result.values.backgrounds[0].url,url.url);
console.log('Background ACK: received Blob, checkpoint, ownership, edits, replacement, archive and source conversion passed.');
