import assert from 'node:assert/strict';
import {readBackgroundRules,shareBackgroundRules} from '../public/assets/js/background-sync-rules.js';
import {backgroundAcknowledgement} from '../public/assets/js/background-sync-ack.js';
import {backgroundRecord,mergeBackgrounds} from '../public/assets/js/background-sync-core.js';
const id=JSON.stringify(['backgrounds','a','name']),general=JSON.stringify(['settings','theme']);
let state={settings:{theme:'dark',syncRules:{[general]:'local',[id]:'cloud'}},syncCheckpoint:{userId:'1'},backgroundCheckpoint:{userId:'1',rules:{[id]:'local'}}};
assert.equal(readBackgroundRules(state,'1')[id],'cloud');
let values=shareBackgroundRules(state,'1');state={...state,...values};
assert.equal(state.settings.syncRules[general],'local');assert.equal(state.settings.syncRules[id],'cloud');assert.equal(state.backgroundCheckpoint.rulesShared,true);
delete state.settings.syncRules[id];assert.deepEqual(readBackgroundRules(state,'1'),{});
values=shareBackgroundRules(state,'1');assert.equal(values.settings.syncRules[id],undefined);
delete state.settings.syncRules;assert.deepEqual(readBackgroundRules(state,'1'),{});assert.deepEqual(shareBackgroundRules(state,'1').settings.syncRules,{});
state.settings.syncRules={[general]:'cloud'};
values=shareBackgroundRules(state,'1',{[id]:'local'});assert.equal(values.settings.syncRules[general],'cloud');assert.equal(values.settings.syncRules[id],'local');
const foreign={...state,syncCheckpoint:{userId:'2'}};
assert.deepEqual(readBackgroundRules(foreign,'1'),{});assert.equal(shareBackgroundRules(foreign,'1',{[id]:'cloud'}).settings,undefined);
assert.deepEqual(readBackgroundRules({...state,backgroundCheckpoint:{userId:'2',rules:{[id]:'local'}}},'3'),{});
const pending=shareBackgroundRules({settings:{syncRules:{[general]:'local'}}},'1',{[id]:'cloud'});
assert.equal(pending.settings,undefined);assert.equal(pending.backgroundCheckpoint.rules[id],'cloud');
const promoted=shareBackgroundRules({...pending,settings:{syncRules:{[general]:'local'}},syncCheckpoint:{userId:'1'}},'1');
assert.equal(promoted.settings.syncRules[id],'cloud');assert.equal(promoted.settings.syncRules[general],'local');
const row={id:'a',name:'Base',type:'image',sourceType:'url',url:'https://example.test/a.png',cloudSync:true};
const base=backgroundRecord(row),left={...base,name:'Local'},right={...base,name:'Cloud'};
assert.equal(mergeBackgrounds({a:base},{a:left},{a:right},readBackgroundRules({...state,settings:promoted.settings},'1')).data.a.name,'Cloud');
const ack=backgroundAcknowledgement({...state,backgrounds:[row]},{userId:'1',before:base,target:base,acknowledged:{...row,version:1},rules:{[id]:'cloud'}});
assert.equal(ack.values.settings.syncRules[general],'cloud');assert.equal(ack.values.settings.syncRules[id],'cloud');assert.equal(ack.values.backgroundCheckpoint.document.a.name,'Base');
assert.equal(ack.values.backgroundCheckpoint.rulesShared,true);
const invalid=shareBackgroundRules(state,'1',{'bad JSON':'local','["backgrounds","__proto__"]':'cloud','["settings","theme"]':'cloud',[id]:'invalid'});
assert.equal(invalid.settings.syncRules[id],undefined);assert.equal(invalid.settings.syncRules[general],'cloud');
assert.throws(()=>backgroundAcknowledgement({...state,backgrounds:[row]},{userId:'1',before:base,target:base,acknowledged:{...row,version:0},rules:{[id]:'cloud'}}),/INVALID_BACKGROUND/);
console.log('Background shared rules: migration, reset, owner isolation, general-rule preservation, selection and atomic ACK passed.');
