import assert from 'node:assert/strict';
import {CommandRegistry} from '../public/assets/js/command-registry.js';
import {CommandExecutor} from '../public/assets/js/command-executor.js';
const registry=new CommandRegistry();let effects=0,asks=0,saves=0,preferences={},answer={confirmed:false},release,failSave=false;
const dispose=registry.register({id:'theme:dark',title:'Dark theme',category:'commands',effect:'state',confirmationKey:'theme-change',run:async value=>{effects++;return value;}});
registry.register({id:'navigate',title:'Open settings',category:'settings',effect:'navigate',run:()=>{effects++;}});
const executor=new CommandExecutor(registry,{preferences:()=>preferences,confirm:async()=>{asks++;return answer;},remember:async(key,value)=>{saves++;if(failSave)throw new Error('storage_unavailable');preferences={...preferences,[key]:value};}});
assert.deepEqual(await executor.execute('theme:dark'),{executed:false});assert.equal(effects,0);assert.equal(saves,0);
answer={confirmed:true,remember:true};assert.deepEqual(await executor.execute('theme:dark','result'),{executed:true,value:'result'});assert.equal(effects,1);assert.equal(saves,1);
await executor.execute('theme:dark');assert.equal(asks,2);assert.equal(effects,2);
await executor.execute('navigate');assert.equal(asks,2);assert.equal(effects,3);
preferences={};failSave=true;await assert.rejects(executor.execute('theme:dark'),/storage_unavailable/);assert.equal(effects,3);
failSave=false;answer={confirmed:true,remember:false};await executor.execute('theme:dark');assert.equal(effects,4);
assert.equal(Object.hasOwn(preferences,'theme-change'),false);
await assert.rejects(executor.execute('missing'),/COMMAND_UNAVAILABLE/);
executor.io.confirm=()=>new Promise(resolve=>{release=resolve;});
const pending=executor.execute('theme:dark');await assert.rejects(executor.execute('navigate'),/COMMAND_BUSY/);dispose();release({confirmed:true,remember:true});
await assert.rejects(pending,/COMMAND_UNAVAILABLE/);assert.equal(effects,4);
registry.register({id:'failure',title:'Failure',category:'commands',effect:'navigate',run:()=>{throw new Error('failed');}});
await assert.rejects(executor.execute('failure'),/failed/);await executor.execute('navigate');assert.equal(effects,5);
console.log('Command execution: cancel, confirmation, per-action skip, failed persistence, concurrent execution and stale registration passed.');
