import assert from 'node:assert/strict';
import {CommandRegistry,commandCategories,commandScore,requiresCommandConfirmation,commandUsageAfter} from '../public/assets/js/command-registry.js';
const registry=new CommandRegistry(),now=1800000000000;let runs=0;
const make=(id,title,category='commands',effect='navigate')=>({id,title,category,effect,run:()=>{runs++;}});
for(const category of commandCategories)registry.register(make(category,`${category} result`,category));
assert.equal(registry.search('result').length,8);assert.equal(runs,0);
assert.deepEqual(registry.search('no matching term').map(row=>row.id),[]);
registry.register({...make('theme','Change theme','commands','state'),keywords:['外観','テーマ'],confirmationKey:'change-theme'});
assert.equal(registry.search('テーマ')[0].id,'theme');assert.equal(registry.search('CHＡNGE  theme')[0].id,'theme');
registry.register(make('exact','Theme','history'));registry.register(make('prefix','Theme settings','commands'));
assert.equal(registry.search('theme',{usage:{prefix:{count:1000000,lastUsed:now}},now})[0].id,'exact');
assert.equal(registry.search('theme s')[0].id,'prefix');
assert.equal(registry.search('chth')[0].id,'theme');
assert.equal(commandScore(registry.get('theme'),'change',{},now)>commandScore(registry.get('theme'),'theme',{},now),true);
assert.equal(commandScore(registry.get('commands'),'',{commands:{count:4,lastUsed:now}},now)>commandScore(registry.get('commands'),'',{},now),true);
assert.equal(commandScore(registry.get('commands'),'',{commands:{count:4,lastUsed:now}},now)>commandScore(registry.get('commands'),'',{commands:{count:4,lastUsed:now-30*86400000}},now),true);
assert.equal(commandScore(registry.get('commands'),'',{commands:{count:-2,lastUsed:now+1}},now),commandScore(registry.get('commands'),'',{},now));
const usage={commands:{count:40,lastUsed:now-100},theme:{count:1,lastUsed:now}};
const groups=registry.initial({usage,now});assert.deepEqual(groups.map(group=>group.id),['recent','frequent','favorites','search','ai']);
assert.equal(groups[0].items[0].id,'theme');assert.equal(groups[1].items[0].id,'commands');
assert.equal(groups[2].items[0].category,'favorites');assert.equal(groups[3].items[0].category,'search');assert.equal(groups[4].items[0].category,'ai');
assert.equal(registry.initial({limitPerGroup:0}).every(group=>group.items.length===0),true);
assert.equal(registry.search('',{limit:0}).length,0);
assert.throws(()=>registry.register(make('commands','Duplicate')),/DUPLICATE_COMMAND/);
for(const invalid of [{...make('__proto__','Bad')},{...make('bad','Bad'),category:'unknown'},{...make('bad','Bad'),effect:'unsafe'},{...make('bad','Bad'),run:'javascript:1'},{...make('bad','Bad'),keywords:['']},{...make('bad','Bad'),confirmationKey:'constructor'}])assert.throws(()=>registry.register(invalid),/INVALID_COMMAND/);
const original={...make('extension:action','Future action'),keywords:['future']};const remove=registry.register(original);original.title='Modified';original.keywords.push('outside');
assert.equal(registry.get('extension:action').title,'Future action');assert.deepEqual(registry.get('extension:action').keywords,['future']);
await registry.get('extension:action').run();assert.equal(runs,1);remove();assert.equal(registry.get('extension:action'),null);
registry.register(make('extension:action','Replaced'));remove();assert.equal(registry.get('extension:action').title,'Replaced');
const state=registry.get('theme');assert.equal(requiresCommandConfirmation(state),true);assert.equal(requiresCommandConfirmation(state,{'change-theme':false}),false);
assert.equal(requiresCommandConfirmation(state,{'change-theme':0}),true);assert.equal(requiresCommandConfirmation(state,Object.create({'change-theme':false})),true);
assert.equal(requiresCommandConfirmation(registry.get('favorites')),false);assert.equal(requiresCommandConfirmation({...state,effect:'search'}),false);
const next=commandUsageAfter(usage,'theme',now+1);assert.equal(next.theme.count,2);assert.equal(next.theme.lastUsed,now+1);assert.equal(usage.theme.count,1);
assert.throws(()=>commandUsageAfter({},'__proto__'),/INVALID_COMMAND/);
const large=Object.fromEntries(Array.from({length:600},(_,i)=>['item:'+i,{count:1,lastUsed:i}]));assert.equal(Object.keys(commandUsageAfter(large,'new',now)).length,500);
assert.ok(commandUsageAfter(large,'new',now).new);assert.equal(registry.search('result',{limit:1000}).length,8);
console.log('Command registry: eight categories, ranking, initial groups, extension lifecycle, usage bounds and confirmation policy passed.');
