import assert from 'node:assert/strict';
import {normalizeFavorite,rankFavorites,sortFavorites,shortcutKey,favoriteShortcuts} from '../public/assets/js/favorites-core.js';
const base={name:'GitHub',url:'https://github.com',tags:'code, work, code',visible:true,pinned:false};
const a=normalizeFavorite(base);
assert.deepEqual(a.tags,['code','work']);
assert.equal(a.url,'https://github.com/');
assert.throws(()=>normalizeFavorite({...base,url:'javascript:alert(1)'}));
assert.throws(()=>normalizeFavorite({...base,shortcut:'F1'}));
assert.equal(shortcutKey('Control+Shift+A'),shortcutKey('shift+control+a'));
const b=normalizeFavorite({...base,name:'Docs',url:'https://example.com',description:'Documentation',tags:'reference'});
assert.equal(rankFavorites([b,a],'gthb')[0].id,a.id);
assert.equal(rankFavorites([a,b],'reference')[0].id,b.id);
assert.equal(rankFavorites([a,b],'documentation')[0].id,b.id);
assert.equal(rankFavorites([{...a,folderId:'folder'},b],'development',[{id:'folder',name:'Development'}])[0].id,a.id);
assert.equal(rankFavorites([a,b],'zzzzzz').length,0);
assert.equal(sortFavorites([{...a,usageCount:10},{...b,usageCount:1}],'usage')[0].id,a.id);
assert.equal(sortFavorites([{...a,pinned:false},{...b,pinned:true}],'manual')[0].id,b.id);
assert.equal(favoriteShortcuts([{...a,pinned:false},{...b,pinned:true}]).get('alt+1').id,b.id);
assert.equal(favoriteShortcuts([{...a,shortcut:'Alt+2'},b]).get('alt+2').id,a.id);
assert.equal(favoriteShortcuts([{...a,visible:false},b]).get('alt+1').id,b.id);
const values=new Map();globalThis.localStorage={getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)};globalThis.window=new EventTarget();window.location={assign:()=>{}};
const model=await import('../public/assets/js/favorites-store.js');
model.saveFolder('Development');const folder=model.folders()[0];
const saved=model.saveFavorite({...base,folderId:folder.id,shortcut:'Alt+1'});
assert.equal(model.favorites().length,1);
assert.throws(()=>model.saveFavorite({...base,name:'Other',shortcut:'Alt+1'}),/shortcut_conflict/);
model.duplicateFavorite(saved.id,' copy');assert.equal(model.favorites().length,2);
model.openFavorite(saved);assert.equal(model.favorites()[0].usageCount,1);assert.ok(model.favorites()[0].lastAccess);
const {setSetting}=await import('../public/assets/js/store.js');
setSetting('favoriteStats',false);model.openFavorite(model.favorites()[0]);assert.equal(model.favorites()[0].usageCount,1);
const copied=model.favorites()[1];model.reorder('favorites',copied.id,saved.id);assert.equal(model.favorites()[0].id,copied.id);
model.deleteFolder(folder.id);assert.equal(model.folders().length,0);assert.ok(model.favorites().every(item=>item.folderId===null));
model.deleteFavorite(saved.id);assert.equal(model.favorites().length,1);
console.log('Favorites: validation, tags, fuzzy ranking, CRUD, folder deletion, reorder, shortcuts and stats passed.');
