import assert from 'node:assert/strict';
import {favoriteLayout, layoutNumber} from '../public/assets/js/favorites-layout.js';
assert.equal(favoriteLayout({width:850,count:20}).limit,10);
assert.equal(favoriteLayout({width:350,count:20}).limit,4);
assert.equal(favoriteLayout({width:100,count:20}).limit,2);
assert.equal(favoriteLayout({width:850,count:4,display:'auto'}).mode,'card');
assert.equal(favoriteLayout({width:850,count:12,display:'auto'}).mode,'icon-name');
assert.equal(favoriteLayout({width:850,count:21,display:'auto'}).mode,'icon');
assert.equal(favoriteLayout({width:350,count:4,display:'auto'}).mode,'icon-name');
assert.equal(favoriteLayout({width:250,count:4,display:'auto'}).mode,'icon');
assert.equal(favoriteLayout({width:850,count:50,limit:15}).limit,15);
assert.equal(favoriteLayout({width:350,count:20,columns:12}).columns,2);
assert.equal(favoriteLayout({width:850,count:20,columns:3}).columns,3);
assert.equal(favoriteLayout({width:850,count:20,display:'card',columns:12}).columns,3);
assert.equal(layoutNumber('100',0,25,100),100);
assert.equal(layoutNumber('101',50,25,100),50);
assert.equal(layoutNumber('12.5',0,0,100),0);
assert.equal(favoriteLayout({width:0,count:20}).columns,1);
console.log('16 favorites layout assertions passed.');
