import assert from 'node:assert/strict';
const rows=name=>({web:[{id:'web',name,url:'https://web.example/?q={query}',prefix:'web',icon:'W',enabled:true,copy:false,sortOrder:0}],ai:[{id:'ai',name:'AI',url:'https://ai.example',prefix:'ai',icon:'A',enabled:true,copy:true,sortOrder:0}]});
const initial=rows('Packaged'),cached=rows('Cached'),fresh=rows('Site default'),values=new Map();
let online=true,calls=0,reply;
globalThis.window=new EventTarget();
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{get onLine(){return online;}}});
globalThis.location={protocol:'chrome-extension:'};
globalThis.document={getElementById:()=>({textContent:JSON.stringify({providers:initial,messages:{},platform:{kind:'extension',serverOrigin:'https://server.example'}})})};
globalThis.localStorage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};
globalThis.fetch=async(url,options)=>{
    calls++;assert.equal(url,'https://server.example/api/provider-presets');assert.equal(options.credentials,'include');assert.equal(options.redirect,'error');
    return new Promise(resolve=>{reply=resolve;});
};
const {storageNamespace}=await import('../public/assets/js/api-transport.js');
const namespace=await storageNamespace();
const custom=[{...initial.web[0],name:'My custom choice'}],checkpoint={userId:'generated',version:7};
values.set(namespace.legacy,JSON.stringify({installationPresets:cached,'providers-web':custom,syncCheckpoint:checkpoint}));
const loader=await import('../public/assets/js/installation-presets.js');
const {presets}=await import('../public/assets/js/i18n.js');
const {get}=await import('../public/assets/js/store.js');
assert.equal(presets.web[0].name,'Cached','cached server defaults remain usable without waiting for network');
assert.equal(calls,1);
const pending=loader.refreshInstallationPresets();
reply(new Response(JSON.stringify({success:true,data:{presets:fresh}})));await pending;
assert.deepEqual(presets,fresh);assert.deepEqual(get('installationPresets'),fresh);
assert.deepEqual(get('providers-web'),custom);assert.deepEqual(get('syncCheckpoint'),checkpoint);
await loader.refreshInstallationPresets();assert.equal(calls,1,'fresh defaults reuse the completed read');
online=false;await assert.rejects(loader.refreshInstallationPresets(true),/OFFLINE/);assert.equal(calls,1);assert.deepEqual(presets,fresh);
online=true;
const bad=loader.refreshInstallationPresets(true);reply(new Response(JSON.stringify({success:true,data:{presets:{web:[],ai:[]}}})));
await assert.rejects(bad,/PRESETS_INVALID/);assert.deepEqual(presets,fresh);assert.deepEqual(get('installationPresets'),fresh);
const outage=loader.refreshInstallationPresets(true);reply(new Response('{}',{status:503}));
await assert.rejects(outage,/PRESETS_UNAVAILABLE/);assert.deepEqual(get('syncCheckpoint'),checkpoint);
const recovery=loader.refreshInstallationPresets(true);reply(new Response(JSON.stringify({success:true,data:{presets:rows('Recovered')}})));await recovery;
assert.equal(presets.web[0].name,'Recovered');assert.deepEqual(get('providers-web'),custom);
console.log('Cached public presets, shared installation refresh, offline retention, outage/invalid response and recovery preserve custom providers and account checkpoints.');
