import assert from 'node:assert/strict';
import {onboardingSteps,onboardingPosition,onboardingPatch,onboardingBackgrounds} from '../public/assets/js/onboarding-core.js';
assert.equal(onboardingSteps().length,8);assert.equal(onboardingSteps(true).length,7);
assert.equal(onboardingSteps(true).includes('discord'),false);
assert.equal(onboardingPosition({step:'ai'},onboardingSteps()),4);
assert.equal(onboardingPosition({step:'discord'},onboardingSteps(true)),0);
assert.deepEqual(onboardingPatch('welcome',{}),{});
assert.deepEqual(onboardingPatch('appearance',{theme:'dark',fontSize:'18',animationLevel:'low'}),{theme:'dark',fontSize:18,animationLevel:'low'});
assert.deepEqual(onboardingPatch('background',{backgroundMode:'solid',backgroundColor:'#abcdef'}),{backgroundMode:'solid',backgroundColor:'#abcdef'});
assert.throws(()=>onboardingPatch('background',{backgroundMode:'solid',backgroundColor:'url(evil)'}));
assert.throws(()=>onboardingPatch('appearance',{theme:'unsafe',fontSize:'18',animationLevel:'low'}));
assert.throws(()=>onboardingPatch('appearance',{theme:'light',fontSize:'99',animationLevel:'rich'}));
assert.deepEqual(onboardingPatch('search',{initialMode:'web',webDefault:'bing'},{web:['bing']}),{initialMode:'web',webDefault:'bing'});
assert.throws(()=>onboardingPatch('search',{initialMode:'web',webDefault:'deleted'},{web:['bing']}));
assert.deepEqual(onboardingPatch('ai',{aiDefault:'chatgpt',aiOrder:'usage'},{ai:['chatgpt']}),{aiDefault:'chatgpt',aiOrder:'usage'});
assert.deepEqual(onboardingPatch('favorites',{favoriteDisplay:'card',webKey:'Shift+Enter',aiKey:'Alt+Enter'}),{favoriteDisplay:'card',webKey:'Shift+Enter',aiKey:'Alt+Enter'});
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'card',webKey:'Control+Shift+A',aiKey:'Shift+Control+A'}));
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'auto',webKey:'Control+Shift+H',aiKey:'Alt+Enter'}));
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'auto',webKey:'Control+K',aiKey:'Alt+Enter'}));
const background={id:'image',name:'Saved image',type:'image',url:'https://example.test/image.png'};
const choices=onboardingBackgrounds([background,{...background,id:'archive',deleted:true},{...background,id:'unsafe',url:'javascript:alert(1)'},background,{...background,id:'preset-night'}]);
assert.deepEqual(choices.map(row=>row.id),['preset-terrace-dusk','preset-night','preset-forest','preset-dawn','image']);
assert.equal(onboardingBackgrounds(null).length,4);
assert.deepEqual(onboardingPatch('background',{backgroundMode:'library',backgroundSelected:'image'},{backgrounds:choices.map(row=>row.id)}),{backgroundMode:'library',backgroundSelected:'image',backgroundSwitch:'manual'});
assert.deepEqual(onboardingPatch('background',{backgroundMode:'library',backgroundSelected:'preset-forest'},{backgrounds:choices.map(row=>row.id)}),{backgroundMode:'library',backgroundSelected:'preset-forest',backgroundSwitch:'manual'});
assert.throws(()=>onboardingPatch('background',{backgroundMode:'library',backgroundSelected:'archive'},{backgrounds:choices.map(row=>row.id)}),/INVALID_INPUT/);
assert.throws(()=>onboardingPatch('background',{backgroundMode:'library',backgroundSelected:'missing'}),/INVALID_INPUT/);
assert.equal(choices[0].type,'image');assert.equal(choices[0].url,'/assets/backgrounds/terrace-dusk.png');
assert.equal(choices.find(row=>row.id==='preset-night').type,'gradient');assert.equal(background.url,'https://example.test/image.png');
console.log('26 onboarding assertions passed.');
