import assert from 'node:assert/strict';
import {onboardingSteps,onboardingPosition,onboardingPatch} from '../public/assets/js/onboarding-core.js';
assert.equal(onboardingSteps().length,8);assert.equal(onboardingSteps(true).length,7);
assert.equal(onboardingSteps(true).includes('discord'),false);
assert.equal(onboardingPosition({step:'ai'},onboardingSteps()),4);
assert.equal(onboardingPosition({step:'discord'},onboardingSteps(true)),0);
assert.deepEqual(onboardingPatch('welcome',{}),{});
assert.deepEqual(onboardingPatch('appearance',{theme:'dark',fontSize:'18',animationLevel:'low'}),{theme:'dark',fontSize:18,animationLevel:'low'});
assert.deepEqual(onboardingPatch('background',{backgroundMode:'solid',backgroundColor:'#abcdef'}),{backgroundMode:'solid',backgroundColor:'#abcdef'});
assert.throws(()=>onboardingPatch('background',{backgroundMode:'solid',backgroundColor:'url(evil)'}));
assert.throws(()=>onboardingPatch('appearance',{theme:'unsafe',fontSize:'18',animationLevel:'low'}));
assert.throws(()=>onboardingPatch('appearance',{theme:'light',fontSize:'99',animationLevel:'rich'}));
assert.deepEqual(onboardingPatch('search',{initialMode:'web',webDefault:'bing'},{web:['bing']}),{initialMode:'web',webDefault:'bing'});
assert.throws(()=>onboardingPatch('search',{initialMode:'web',webDefault:'deleted'},{web:['bing']}));
assert.deepEqual(onboardingPatch('ai',{aiDefault:'chatgpt',aiOrder:'usage'},{ai:['chatgpt']}),{aiDefault:'chatgpt',aiOrder:'usage'});
assert.deepEqual(onboardingPatch('favorites',{favoriteDisplay:'card',webKey:'Shift+Enter',aiKey:'Alt+Enter'}),{favoriteDisplay:'card',webKey:'Shift+Enter',aiKey:'Alt+Enter'});
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'card',webKey:'Control+Shift+A',aiKey:'Shift+Control+A'}));
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'auto',webKey:'Control+Shift+H',aiKey:'Alt+Enter'}));
assert.throws(()=>onboardingPatch('favorites',{favoriteDisplay:'auto',webKey:'Control+K',aiKey:'Alt+Enter'}));
console.log('18 onboarding assertions passed.');
