import assert from 'node:assert/strict';
import {validShortcut,keySignature,matchesShortcut,directUrl,orderProviders,boundedInteger} from '../public/assets/js/search-preferences.js';
assert.ok(validShortcut('Control+Enter'));
assert.ok(!validShortcut('Enter'));
assert.ok(!validShortcut('Control+K'));
assert.ok(!validShortcut('Alt+1'));
assert.ok(!validShortcut('Shift+Shift+A'));
assert.equal(keySignature('Shift+Control+H'),'control+shift+h');
assert.ok(matchesShortcut({key:'H',ctrlKey:true,shiftKey:true},'Control+Shift+H'));
assert.ok(!matchesShortcut({key:'Enter',altKey:true,shiftKey:true},'Alt+Enter'));
assert.equal(directUrl('example.com','suggest'),null);
assert.equal(directUrl('example.com','full'),null);
assert.equal(directUrl('https://example.com','full'),'https://example.com/');
assert.equal(directUrl('example.com','auto'),'https://example.com/');
assert.equal(directUrl('javascript:alert(1)','auto'),null);
assert.equal(boundedInteger(-1,300,1,10000),300);
assert.equal(orderProviders([{id:'a'},{id:'b'}],'usage',{b:{count:2}})[0].id,'b');
assert.equal(orderProviders([{id:'a'},{id:'b'}],'recent',{b:{last:2},a:{last:1}})[0].id,'b');
const saved=new Map();globalThis.localStorage={getItem:key=>saved.get(key),setItem:(key,value)=>saved.set(key,value)};globalThis.window=new EventTarget();
const {set,setSetting}=await import('../public/assets/js/store.js');
const {history,record}=await import('../public/assets/js/history.js');
setSetting('historyLimit',2);
record('one','test','web');record('two','test','web');record('three','test','web');
assert.deepEqual(history().map(item=>item.query),['three','two']);
setSetting('historyDays',1);
set('history',[{id:'old',query:'old',at:Date.now()-2*86400000},{id:'new',query:'new',at:Date.now()}]);
assert.deepEqual(history().map(item=>item.id),['new']);
console.log('18 search preference assertions passed.');
