import assert from 'node:assert/strict';
import {safeUrl, detectUrl, recommendAi, prefixQuery, queryUrl, validProvider} from '../public/assets/js/search-core.js';
const provider = {id:'test',name:'Test',url:'https://example.com/?q={query}',prefix:'t'};
assert.equal(safeUrl('javascript:alert(1)'), null);
assert.equal(safeUrl('https://name:secret@example.com'), null);
assert.equal(detectUrl('example.com/path'), 'https://example.com/path');
assert.equal(detectUrl('two words.com'), null);
assert.equal(detectUrl('file:///private'), null);
assert.equal(recommendAi('short'), false);
assert.equal(recommendAi('a'.repeat(25)), true);
assert.equal(recommendAi('方法'), true);
assert.equal(recommendAi('one\ntwo'), true);
assert.equal(prefixQuery('!t a & b', {web:[provider],ai:[]}).query, 'a & b');
assert.equal(prefixQuery('unknown query', {web:[provider],ai:[]}), null);
assert.equal(queryUrl(provider, '日本語 &?#'), 'https://example.com/?q=%E6%97%A5%E6%9C%AC%E8%AA%9E%20%26%3F%23');
assert.ok(validProvider(provider));
assert.ok(!validProvider({...provider,url:'javascript:{query}'}));
assert.ok(!validProvider({...provider,url:'https://example.com'}));
assert.ok(!validProvider(null));
const values = new Map();
globalThis.localStorage = {getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)};
globalThis.window = new EventTarget();
const {set, setSetting} = await import('../public/assets/js/store.js');
const {history,record,removeHistory,clearHistory} = await import('../public/assets/js/history.js');
for(let i=0;i<305;i++) record(`query ${i}`,'test','web');
assert.equal(history().length,300);
assert.equal(history()[0].query,'query 304');
const id = history()[0].id; removeHistory(id);
assert.equal(history().length,299);
assert.ok(!history().some(row=>row.id===id));
setSetting('saveHistory',false); record('private','test','web');
assert.equal(history().length,299);
set('history',[{id:'expired',query:'expired',at:Date.now()-91*86400000},{id:'now',query:'now',at:Date.now()}]);
assert.equal(history().length,1);
clearHistory(); assert.equal(history().length,0);
console.log('Search core and history: 23 assertions passed.');
