import assert from 'node:assert/strict';
globalThis.window=new EventTarget();
let persisted=JSON.stringify({settings:{syncHistory:false},backgrounds:[{id:'local',localOnly:true}]});
let fail=false;
globalThis.localStorage={getItem:()=>persisted,setItem:(key,value)=>{if(fail)throw new Error('quota');persisted=value;}};
const store=await import('../public/assets/js/store.js');
store.setMany({favorites:[{id:'synced'}],syncCheckpoint:{version:2}});
assert.equal(store.get('syncCheckpoint').version,2);
assert.equal(JSON.parse(persisted).backgrounds[0].id,'local');
const original=persisted;fail=true;
assert.throws(()=>store.setMany({favorites:[],syncCheckpoint:{version:3}}),/quota/);
assert.equal(store.get('favorites')[0].id,'synced');assert.equal(store.get('syncCheckpoint').version,2);assert.equal(persisted,original);
fail=false;persisted=JSON.stringify({settings:{syncHistory:true},favorites:[{id:'other-tab'}],syncCheckpoint:{version:4}});
const changes=[];window.addEventListener('data-change',event=>changes.push(event.detail));
const event=new Event('storage');event.key='search-startpage-v1';window.dispatchEvent(event);
assert.equal(store.setting('syncHistory'),true);assert.equal(store.get('favorites')[0].id,'other-tab');assert.equal(store.get('syncCheckpoint').version,4);
assert.ok(changes.includes('favorites'));assert.ok(changes.includes('settings'));
const copy=store.snapshot();copy.favorites.length=0;assert.equal(store.get('favorites').length,1);
store.setMany(state=>({settings:{...state.settings,testCleanup:true}}),()=>[]);assert.equal(store.setting('testCleanup'),true);
assert.throws(()=>store.setMany({},()=>[{id:'file',blob:new Blob(['file'])}]),/require_indexeddb/);
console.log('14 store assertions passed.');
