import assert from 'node:assert/strict';
import {syncDocument,syncValues} from '../public/assets/js/sync-data.js';
const presets={web:[{id:'google',url:'https://google.com/?q={query}'}],ai:[]};
const state={settings:{theme:'dark',syncHistory:false,clearSyncedOnLogout:true},history:[{id:'secret',query:'private',at:10}],backgrounds:[{id:'file',localOnly:true}],favorites:[{id:'f',name:'old'}]};
const cloudHistory={remote:{id:'remote',query:'cloud',at:1}};
const document=syncDocument(state,presets,cloudHistory);
assert.deepEqual(document.settings,{theme:'dark'});assert.deepEqual(document.history,cloudHistory);
assert.equal(document.backgrounds,undefined);assert.equal(document['providers-web'].google.id,'google');
const checkpoint={userId:'1',document};document.favorites.new={id:'new',name:'unsynced'};
checkpoint.document=structuredClone(document);delete checkpoint.document.favorites.new;
const values=syncValues(state,document,checkpoint,'now',presets);
assert.equal(values.history,undefined);assert.equal(values.syncOwnership.collections.history,undefined);
assert.deepEqual(values.syncOwnership.collections.favorites,['f']);assert.equal(values.favorites.length,2);
assert.equal(values.settings.syncHistory,false);assert.equal(values.settings.clearSyncedOnLogout,true);
assert.equal(values.backgrounds,undefined);assert.equal(values.syncCheckpoint,checkpoint);
const withHistory=syncValues({...state,settings:{syncHistory:true}}, {history:{a:{id:'a',at:1},b:{id:'b',at:2}}}, {userId:'1',document:{history:{a:{id:'a'}}}},'now',presets);
assert.deepEqual(withHistory.history.map(row=>row.id),['b','a']);assert.equal(withHistory['providers-web'][0].id,'google');
assert.deepEqual(syncValues(state,{'providers-web':{}},{userId:'1',document:{}},'now',presets)['providers-web'],[]);
assert.equal(syncDocument({...state,settings:{syncHistory:true}},presets).history.secret.query,'private');
const ordered=syncDocument({'providers-web':[{id:'b'},{id:'a'}]},presets);
assert.equal(ordered['providers-web'].a.sortOrder,1);
assert.deepEqual(syncValues({}, {'providers-web':{a:ordered['providers-web'].a,b:ordered['providers-web'].b}},{userId:'1',document:{}},'now',presets)['providers-web'].map(row=>row.id),['b','a']);
const enabledHistory=syncDocument({...state,settings:{syncHistory:true},syncCheckpoint:{preferences:{historyEnabled:false}}},presets,cloudHistory);
assert.deepEqual(Object.keys(enabledHistory.history).sort(),['remote','secret']);
const continuedHistory=syncDocument({...state,settings:{syncHistory:true},history:[],syncCheckpoint:{preferences:{historyEnabled:true}}},presets,cloudHistory);
assert.deepEqual(continuedHistory.history,{});
assert.equal(syncValues({...state,settings:{syncHistory:true},syncHistoryMergePending:true},document,checkpoint,'now',presets).syncHistoryMergePending,false);
assert.deepEqual(Object.keys(syncDocument({...state,settings:{syncHistory:true},syncHistoryMergePending:true},presets,cloudHistory,null).history),['secret']);
const offAfterSync=syncValues({...state,history:[{id:'owned'},{id:'private'}],syncOwnership:{userId:'1',collections:{history:['owned','removed']}}},document,checkpoint,'now',presets);
assert.deepEqual(offAfterSync.syncOwnership.collections.history,['owned']);
assert.equal(syncDocument({...state,settingsHistory:{entries:[{label:'theme'}],cursor:1}},presets,cloudHistory).settingsHistory,undefined);
assert.equal(syncDocument({...state,onboarding:{step:'search',complete:false}},presets).onboarding,undefined);
console.log('25 sync data assertions passed.');
