import assert from 'node:assert/strict';
import {mergeSync, resolveSync, collectionMap} from '../public/assets/js/sync-core.js';
const base={settings:{theme:'dark',font:16},favorites:collectionMap([{id:'a',name:'A',url:'https://a.test'}])};
const local=structuredClone(base),cloud=structuredClone(base);
local.settings.theme='light';cloud.settings.font=18;
assert.deepEqual(mergeSync(base,local,cloud),{data:{...base,settings:{theme:'light',font:18}},conflicts:[]});
local.favorites.a.name='Local';cloud.favorites.a.url='https://cloud.test';
assert.deepEqual(mergeSync(base,local,cloud).data.favorites.a,{id:'a',name:'Local',url:'https://cloud.test'});
cloud.settings.theme='custom';
const result=mergeSync(base,local,cloud);
assert.equal(result.conflicts.length,1);
const conflict=result.conflicts[0];
assert.deepEqual(conflict.path,['settings','theme']);
assert.deepEqual(conflict.previous,{present:true,value:'dark'});
assert.deepEqual(conflict.local,{present:true,value:'light'});
assert.deepEqual(conflict.cloud,{present:true,value:'custom'});
assert.throws(()=>resolveSync(base,local,cloud,{}),/unresolved/);
assert.equal(resolveSync(base,local,cloud,{[conflict.id]:'cloud'}).settings.theme,'custom');
assert.equal(mergeSync(base,local,cloud,{[conflict.id]:'local'}).conflicts.length,0);
const deleted=structuredClone(base);delete deleted.favorites.a;
assert.deepEqual(mergeSync(base,deleted,base).data.favorites,{});
const edited=structuredClone(base);edited.favorites.a.name='Edited';
const deleteConflict=mergeSync(base,deleted,edited).conflicts[0];
assert.equal(deleteConflict.local.present,false);
assert.deepEqual(resolveSync(base,deleted,edited,{[deleteConflict.id]:'local'}).favorites,{});
assert.equal(resolveSync(base,deleted,edited,{[deleteConflict.id]:'cloud'}).favorites.a.name,'Edited');
assert.deepEqual(mergeSync({}, {one:{value:1}}, {two:{value:2}}).data,{one:{value:1},two:{value:2}});
assert.equal(mergeSync({x:null},{x:1},{x:2}).conflicts[0].previous.present,true);
assert.equal(mergeSync({tags:['a']},{tags:['b']},{tags:['c']}).conflicts.length,1);
assert.equal(mergeSync({x:{a:1,b:2}},{x:{b:2,a:1}},{x:{a:1,b:3}}).conflicts.length,0);
assert.throws(()=>collectionMap([{id:'a'},{id:'a'}]),/invalid_sync_id/);
assert.throws(()=>collectionMap([{id:'__proto__'}]),/invalid_sync_id/);
assert.throws(()=>mergeSync({},JSON.parse('{"__proto__":{"polluted":true}}'),{}),/invalid_sync_key/);
assert.equal({}.polluted,undefined);
assert.equal(base.settings.theme,'dark');
console.log('23 sync merge assertions passed.');
