<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\UpdateCommands;
use App\Repositories\{UpdateHistoryRepository,AdminRepository};
use App\Database\{Database,Migrator};
use App\Http\HttpException;
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1'||!in_array(getenv('TEST_BACKUP_HOST'),['search-update-backup-mysql-20261004','search-update-backup-mariadb-20261004'],true))exit(1);
$directory=sys_get_temp_dir().'/update-commands-'.bin2hex(random_bytes(8));mkdir($directory,0700);$count=0;$pdo=null;$now=1800000000;
$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$reject=static function(callable $call,string $code)use($check){try{$call();throw new LogicException('Unexpected request success');}catch(HttpException $error){$check($error->errorCode===$code,$code);}};
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
try{
    $pdo=Database::connect(['host'=>getenv('TEST_BACKUP_HOST'),'port'=>3306,'name'=>'update_backup','user'=>'backup','password'=>getenv('TEST_BACKUP_PASSWORD')]);$check($pdo->query('SHOW TABLES')->fetchAll()===[],'dedicated command schema starts empty');
    $migrator=new Migrator($pdo,dirname(__DIR__).'/database/migrations');$check(count($migrator->migrate())===17,'all 17 migrations create command audit history');$check($migrator->migrate()===[],'migration repeat preserves history schema');
    foreach([1,2] as $id)$pdo->prepare('INSERT INTO users(id,discord_id,discord_username,locale,created_at,updated_at) VALUES(?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([$id,'99999999999999999'.$id,'生成ユーザー','ja']);
    $pdo->prepare('INSERT INTO administrators(user_id,created_at,updated_at) VALUES(?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([1]);$admin=new AdminRepository($pdo);$history=new UpdateHistoryRepository($pdo);
    $make=static fn(string $name,?Closure $audit=null)=>new UpdateCommands($directory.'/'.$name,fn(int $actor)=>$admin->isAdministrator($actor),$audit??fn(array $request,string $event)=>$history->record($request,$event),fn(array $request)=>$history->matches($request),static function()use(&$now){return $now;});
    $service=$make('main');$selection=['from_version'=>'0.1.0-dev','to_version'=>'2.0.0','channel'=>'stable','repository'=>'owner/repository','release_id'=>12];$state=$service->status();
    $check($state['request']===null&&!is_file($directory.'/main/commands.json'),'status creates no pretend accepted request');$reject(fn()=>$service->enqueue(2,'apply',$selection,0),'FORBIDDEN');$check($service->status()['revision']===0,'unauthorized request changes no ledger');
    $state=$service->enqueue(1,'apply',$selection,0);$request=$state['request'];$check($request['status']==='queued'&&$request['audited']&&$history->matches($request),'only DB-audited request becomes queued');
    $check($history->listing()[0]['status']==='queued'&&(int)$pdo->query("SELECT COUNT(*) FROM log_entries WHERE error_code='UPDATE_APPLY_REQUESTED'")->fetchColumn()===1,'acceptance history and audit committed together');$check((fileperms($directory.'/main/commands.json')&0077)===0,'private command ledger permissions');
    $reject(fn()=>$service->enqueue(1,'apply',$selection,0),'UPDATE_STATE_CHANGED');$reject(fn()=>$service->enqueue(1,'apply',$selection,$state['revision']),'UPDATE_IN_PROGRESS');
    $state=$service->claim($state['revision']);$check($state['request']['status']==='running'&&$history->listing()[0]['status']==='running','claim records start before returning executable request');$reject(fn()=>$service->claim($state['revision']),'UPDATE_IN_PROGRESS');
    $reject(fn()=>$service->finish(str_repeat('0',32),$state['revision'],'complete'),'UPDATE_STATE_CHANGED');$state=$service->finish($request['id'],$state['revision'],'complete');$check($state['request']['audited']&&$history->listing()[0]['status']==='complete'&&$history->listing()[0]['completed_at']!==null,'completed command persists and projects once');
    $events=(int)$pdo->query('SELECT COUNT(*) FROM log_entries')->fetchColumn();$history->record($state['request'],'finished');$check((int)$pdo->query('SELECT COUNT(*) FROM log_entries')->fetchColumn()===$events,'repeat terminal projection does not duplicate audit');
    $tampered=$state['request'];$tampered['to_version']='3.0.0';$reject(fn()=>$history->record($tampered,'finished'),'UPDATE_STATE_CHANGED');$check($history->listing()[0]['to_version']==='2.0.0','same ID cannot rewrite accepted target');
    $replayed=array_replace($state['request'],['status'=>'prepared','completed_at'=>null,'audited'=>false]);$reject(fn()=>$history->record($replayed,'requested'),'UPDATE_STATE_CHANGED');$check($history->listing()[0]['status']==='complete','old acceptance cannot downgrade completed history');
    $rollback=$selection;$rollback['from_version']='2.0.0';$rollback['to_version']='0.1.0-dev';$rollback['release_id']=null;$state=$service->enqueue(1,'rollback',$rollback,$state['revision']);$check(count($state['history'])===1&&$state['request']['operation']==='rollback','manual rollback accepted independently from completed update');$state=$service->claim($state['revision']);$state=$service->finish($state['request']['id'],$state['revision'],'rolled_back');$check($history->listing()[0]['status']==='rolled_back','manual rollback outcome in DB history');
    $failed=$make('audit-failure',static function(){throw new RuntimeException('fixture secret');});$reject(fn()=>$failed->enqueue(1,'apply',$selection,0),'UPDATE_AUDIT_FAILED');$check($failed->status()['request']['status']==='failed'&&!$failed->status()['request']['audited'],'audit failure never yields runnable queued request');$check(!str_contains(file_get_contents($directory.'/audit-failure/commands.json'),'fixture secret'),'arbitrary exception text excluded');
    $pdo->exec('RENAME TABLE log_entries TO fixture_log_entries');try{$atomic=$make('atomic');$reject(fn()=>$atomic->enqueue(1,'apply',$selection,0),'UPDATE_AUDIT_FAILED');$check(!$history->matches($atomic->status()['request']),'failed audit SQL rolls back newly inserted history row');}finally{$pdo->exec('RENAME TABLE fixture_log_entries TO log_entries');}
    $prepared=$make('prepared');$state=$prepared->enqueue(1,'apply',$selection,0);$state['request']['status']='prepared';$state['request']['audited']=false;file_put_contents($directory.'/prepared/commands.json',json_encode($state));$state=$prepared->claim($state['revision']);$check($state['request']['status']==='running','crash after DB audit before queue publication reconciles safely');$prepared->finish($state['request']['id'],$state['revision'],'failed','UPDATE_INTERRUPTED');
    $state=$failed->status();$state['request']=array_replace($state['request'],['status'=>'prepared','completed_at'=>null,'error'=>null]);file_put_contents($directory.'/audit-failure/commands.json',json_encode($state));$missing=$make('audit-failure');$reject(fn()=>$missing->claim($state['revision']),'UPDATE_AUDIT_FAILED');$check($missing->status()['request']['status']==='failed','crash before DB audit cannot execute');
    $revoked=$make('revoked');$state=$revoked->enqueue(1,'apply',$selection,0);$pdo->prepare('UPDATE administrators SET admin_flag=0 WHERE user_id=?')->execute([1]);$reject(fn()=>$revoked->claim($state['revision']),'FORBIDDEN');$check($revoked->status()['request']['status']==='failed','revoked administrator request cannot execute');$pdo->prepare('UPDATE administrators SET admin_flag=1 WHERE user_id=?')->execute([1]);
    $breakProjection=false;$projection=$make('projection',static function($request,$event)use($history,&$breakProjection){if($event==='finished'&&$breakProjection)throw new RuntimeException('fixture secret');$history->record($request,$event);});$state=$projection->enqueue(1,'apply',$selection,0);$state=$projection->claim($state['revision']);$breakProjection=true;$reject(fn()=>$projection->finish($state['request']['id'],$state['revision'],'complete'),'UPDATE_AUDIT_FAILED');$state=$projection->status();$check($state['request']['status']==='complete'&&!$state['request']['audited'],'real outcome persists when DB projection unavailable');$breakProjection=false;$state=$projection->reconcile($state['revision']);$check($state['request']['audited']&&$history->listing()[0]['status']==='complete','pending terminal audit retries without reexecuting update');
    $invalid=$selection;$invalid['token']='fixture secret';$reject(fn()=>$service->enqueue(1,'apply',$invalid,$service->status()['revision']),'INVALID_INPUT');
    for($i=0;$i<22;$i++){$state=$service->enqueue(1,'apply',$selection,$service->status()['revision']);$state=$service->claim($state['revision']);$service->finish($state['request']['id'],$state['revision'],'failed','UPDATE_INTERRUPTED');}$check(count($service->status()['history'])===20&&count($history->listing(100))>=22,'private history bounded while DB preserves all update records');
    $path=$directory.'/main/commands.json';$json=file_get_contents($path);file_put_contents($path,'broken fixture secret');$reject(fn()=>$service->status(),'UPDATE_COMMAND_INVALID');$check(file_get_contents($path)==='broken fixture secret','corrupt ledger never silently reset');file_put_contents($path,$json);
    $before=count($history->listing(100));$pdo->prepare('DELETE FROM users WHERE id=?')->execute([2]);$check(count($history->listing(100))===$before,'history remains independent from account cleanup');
    $concurrent=$make('concurrent');$state=$concurrent->enqueue(1,'apply',$selection,0);$child=$directory.'/claim.php';file_put_contents($child,'<?php require '.var_export(dirname(__DIR__).'/app/autoload.php',true).';$pdo=App\\Database\\Database::connect(["host"=>getenv("TEST_BACKUP_HOST"),"port"=>3306,"name"=>"update_backup","user"=>"backup","password"=>getenv("TEST_BACKUP_PASSWORD")]);$admin=new App\\Repositories\\AdminRepository($pdo);$history=new App\\Repositories\\UpdateHistoryRepository($pdo);$commands=new App\\Services\\UpdateCommands($argv[1],fn($id)=>$admin->isAdministrator($id),fn($r,$e)=>$history->record($r,$e),fn($r)=>$history->matches($r));try{$commands->claim((int)$argv[2]);echo "ok";}catch(App\\Http\\HttpException $e){if($e->errorCode!=="UPDATE_STATE_CHANGED")exit(2);echo "stale";}');chmod($child,0600);$children=[];
    for($i=0;$i<2;$i++){$process=proc_open([PHP_BINARY,$child,$directory.'/concurrent',(string)$state['revision']],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$children[]=[$process,$pipes];}$outputs=[];$good=true;foreach($children as [$process,$pipes]){$outputs[]=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$good=$good&&proc_close($process)===0&&$err==='';}sort($outputs);$check($good&&$outputs===['ok','stale']&&$concurrent->status()['request']['status']==='running','two real processes claim exactly one executable command');$state=$concurrent->status();$concurrent->finish($state['request']['id'],$state['revision'],'failed','UPDATE_INTERRUPTED');
    $migration=require dirname(__DIR__).'/database/migrations/017_update_history.php';$migration->down($pdo);$check($pdo->query("SHOW TABLES LIKE 'update_history'")->fetchAll()===[],'history migration down succeeds');$migration->up($pdo);$check($history->listing()===[],'history migration can be recreated');
    echo "$count isolated update command/history checks passed.\n";
}finally{if($pdo!==null){$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $name){if(!preg_match('/^[A-Za-z0-9_]+$/D',$name))throw new RuntimeException('Unexpected fixture table');$pdo->exec('DROP TABLE `'.$name.'`');}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}$remove($directory);}
