<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\{UpdateCompatibility,UpdatePackage,ReleasePackageBuilder};
use App\Http\HttpException;
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1')exit(1);
$directory=sys_get_temp_dir().'/update-compat-'.bin2hex(random_bytes(8));mkdir($directory,0700);$count=0;$root=dirname(__DIR__);
$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
try{
    $before=hash_file('sha256',$root.'/config/config.php');(new ReleasePackageBuilder())->build($root,$directory.'/release.tar');$version=trim(file_get_contents($root.'/VERSION'));
    $manifest=(new UpdatePackage())->verify($directory.'/release.tar',$directory.'/stage',$version,true);$validator=new UpdateCompatibility();$stage=$directory.'/stage';
    $check($validator->validate($stage,$manifest)===12,'real candidate HTTP worker descriptor scheduler and journal binding checks');
    $check(!file_exists($stage.'/config/config.php')&&!file_exists($stage.'/storage'),'probe configuration and storage removed');
    foreach($manifest['files'] as $path=>$meta)if(hash_file('sha256',$stage.'/'.$path)!==$meta['sha256'])throw new RuntimeException('Candidate changed');$check(true,'all managed candidate hashes unchanged');
    $check(hash_file('sha256',$root.'/config/config.php')===$before,'real application configuration untouched');
    $original=file_get_contents($stage.'/public/index.php');$bad=$manifest;$body='<?php http_response_code(200);echo "unsafe";';file_put_contents($stage.'/public/index.php',$body);$bad['files']['public/index.php']=['bytes'=>strlen($body),'sha256'=>hash('sha256',$body)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate HTTP without update stop rejected');}$check(!file_exists($stage.'/config/config.php')&&!file_exists($stage.'/storage'),'incompatible candidate probe artifacts cleaned');file_put_contents($stage.'/public/index.php',$original);
    $worker=$stage.'/bin/update-check-worker.php';$originalWorker=file_get_contents($worker);$body='<?php echo json_encode(["status"=>"success"]);';file_put_contents($worker,$body);$bad=$manifest;$bad['files']['bin/update-check-worker.php']=['bytes'=>strlen($body),'sha256'=>hash('sha256',$body)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate worker without pause rejected');}file_put_contents($worker,$originalWorker);
    file_put_contents($stage.'/config/config.php','existing config');try{$validator->validate($stage,$manifest);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','existing stage configuration never overwritten');}$check(file_get_contents($stage.'/config/config.php')==='existing config','existing stage config preserved');unlink($stage.'/config/config.php');
    mkdir($stage.'/storage');file_put_contents($stage.'/storage/existing','preserve');try{$validator->validate($stage,$manifest);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','existing stage storage rejected');}$check(file_get_contents($stage.'/storage/existing')==='preserve','existing stage storage preserved');unlink($stage.'/storage/existing');rmdir($stage.'/storage');
    $journalPath=$stage.'/app/Services/UpdateJournal.php';$journalSource=file_get_contents($journalPath);$legacyBody='<?php namespace App\Services; final class UpdateJournal { public function __construct($directory){} public function start($from,$to,$revision){return ["format"=>2];} public function status(){return ["format"=>2];} }';file_put_contents($journalPath,$legacyBody);$bad=$manifest;$bad['files']['app/Services/UpdateJournal.php']=['bytes'=>strlen($legacyBody),'sha256'=>hash('sha256',$legacyBody)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate without durable request binding refused');}file_put_contents($journalPath,$journalSource);
    $runnerPath=$stage.'/bin/run-update.php';$runnerSource=file_get_contents($runnerPath);unlink($runnerPath);$bad=$manifest;unset($bad['files']['bin/run-update.php']);
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate cannot remove next worker entry');}file_put_contents($runnerPath,$runnerSource);
    $checksPath=$stage.'/app/Services/UpdateChecks.php';$checksSource=file_get_contents($checksPath);$legacyChecks='<?php namespace App\Services; final class UpdateChecks {}';file_put_contents($checksPath,$legacyChecks);$bad=$manifest;$bad['files']['app/Services/UpdateChecks.php']=['bytes'=>strlen($legacyChecks),'sha256'=>hash('sha256',$legacyChecks)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate without server selection locking refused');}file_put_contents($checksPath,$checksSource);
    $schedulerPath=$stage.'/bin/update-execution-worker.php';$schedulerSource=file_get_contents($schedulerPath);unlink($schedulerPath);$bad=$manifest;unset($bad['files']['bin/update-execution-worker.php']);
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate cannot remove execution scheduler');}file_put_contents($schedulerPath,$schedulerSource);
    $body='<?php echo "unsafe";';file_put_contents($schedulerPath,$body);$bad=$manifest;$bad['files']['bin/update-execution-worker.php']=['bytes'=>strlen($body),'sha256'=>hash('sha256',$body)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate scheduler without singleton refusal rejected');}file_put_contents($schedulerPath,$schedulerSource);
    $entryPath=$stage.'/public/index.php';$entrySource=file_get_contents($entryPath);$body=str_replace('App\\Services\\UpdateWebCache::synchronize(dirname(__DIR__),$updateAccess->generation());','/* cache hook removed */',$entrySource);if($body===$entrySource)throw new RuntimeException('Cache hook fixture changed');file_put_contents($entryPath,$body);$bad=$manifest;$bad['files']['public/index.php']=['bytes'=>strlen($body),'sha256'=>hash('sha256',$body)];
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate HTTP without cache coordination refused');}file_put_contents($entryPath,$entrySource);
    $cachePath=$stage.'/app/Services/UpdateWebCache.php';$cacheSource=file_get_contents($cachePath);unlink($cachePath);$bad=$manifest;unset($bad['files']['app/Services/UpdateWebCache.php']);
    try{$validator->validate($stage,$bad);throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode==='UPDATE_GATE_INCOMPATIBLE','candidate cannot remove Web cache coordinator');}file_put_contents($cachePath,$cacheSource);
    $check($validator->validate($stage,$manifest)===12,'clean candidate reusable after rejected probes');
    echo "$count candidate compatibility checks passed.\n";
}finally{$remove($directory);}
