<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\{UpdateDatabase,UpdateDatabaseMerge};
use App\Database\{Database,Migrator};
use App\Http\HttpException;
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1'||!in_array(getenv('TEST_BACKUP_HOST'),['search-update-backup-mysql-20261004','search-update-backup-mariadb-20261004'],true))exit(1);
$pdo=Database::connect(['host'=>getenv('TEST_BACKUP_HOST'),'port'=>3306,'name'=>'update_backup','user'=>'backup','password'=>getenv('TEST_BACKUP_PASSWORD')]);$directory=sys_get_temp_dir().'/db-merge-'.bin2hex(random_bytes(8));mkdir($directory,0700);$count=0;$database=new UpdateDatabase($pdo);$merger=new UpdateDatabaseMerge($pdo);
$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$snapshot=static function(string $name)use($database,$directory){$path=$directory.'/'.$name.'.jsonl';return ['path'=>$path,'metadata'=>$database->snapshot($path)];};
$reject=static function(callable $action,string $code)use($check){try{$action();throw new LogicException('Unexpected success');}catch(HttpException $e){$check($e->errorCode===$code,$code);}};
try{
    $check($pdo->query('SHOW TABLES')->fetchAll()===[],'merge uses dedicated empty schema');(new Migrator($pdo,dirname(__DIR__).'/database/migrations'))->migrate();
    $pdo->exec('CREATE TABLE merge_items(id INT PRIMARY KEY,content VARCHAR(255) NOT NULL UNIQUE,note TEXT NULL,payload MEDIUMBLOB NULL) ENGINE=InnoDB');
    $pdo->exec('CREATE TABLE merge_links(item_id INT NOT NULL,item_key VARCHAR(32) NOT NULL,content TEXT,PRIMARY KEY(item_id,item_key),FOREIGN KEY(item_id) REFERENCES merge_items(id) ON DELETE CASCADE) ENGINE=InnoDB');
    $insert=$pdo->prepare('INSERT INTO merge_items VALUES(?,?,?,?)');foreach([[1,'old1',null,"old\0binary"],[2,'old2',null,null],[3,'old3',null,null]] as $row)$insert->execute($row);$pdo->exec("INSERT INTO merge_links VALUES(1,'old','keep')");
    $pdo->prepare('INSERT INTO users(id,discord_id,discord_username,locale,created_at,updated_at) VALUES(1,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['999999999999999997','old name','en']);$before=$snapshot('before');
    $pdo->exec("UPDATE merge_items SET content='migration1',note='migration note' WHERE id=1");$pdo->exec("INSERT INTO merge_items VALUES(4,'migration4',NULL,NULL)");$pdo->exec("UPDATE users SET discord_username='migration name' WHERE id=1");$pdo->exec('CREATE TABLE merge_added(id INT PRIMARY KEY,value TEXT) ENGINE=InnoDB');$pdo->exec("INSERT INTO merge_added VALUES(1,'migration seed')");$baseline=$snapshot('baseline');
    $pdo->prepare('UPDATE merge_items SET content=?,payload=? WHERE id=1')->execute(['user1',"user\0bytes\xff"]);$pdo->exec("UPDATE merge_items SET note='user note' WHERE id=2");$pdo->exec('DELETE FROM merge_items WHERE id=3');$pdo->exec("INSERT INTO merge_items VALUES(5,'user5',NULL,NULL)");$pdo->exec("INSERT INTO merge_links VALUES(5,'new','user link')");$pdo->exec("UPDATE users SET locale='ja' WHERE id=1");
    $pdo->prepare('INSERT INTO users(id,discord_id,discord_username,locale,created_at,updated_at) VALUES(200,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['999999999999999996','temporary later user','en']);$pdo->exec('DELETE FROM users WHERE id=200');$current=$snapshot('current');
    $output=$directory.'/merged.jsonl';$metadata=$merger->prepare($before,$baseline,$current,$output);$check((fileperms($output)&0777)===0600,'merged snapshot is private');$check($pdo->query("SELECT content FROM merge_items WHERE id=1")->fetchColumn()==='user1'&&$pdo->query("SHOW TABLES LIKE 'merge_added'")->fetchAll()!==[],'preparation never changes live user rows or schema');
    $database->restore($output,$metadata);$rows=$pdo->query('SELECT * FROM merge_items ORDER BY id')->fetchAll(PDO::FETCH_NUM);$check(count($rows)===3&&array_map(static fn($row)=>(int)$row[0],$rows)===[1,2,5],'user insert and deletion retained, unchanged migration insert undone');
    $check($rows[0][1]==='user1'&&$rows[0][2]===null&&$rows[0][3]==="user\0bytes\xff",'field merge preserves user edit and binary while undoing untouched migration field');$check($rows[1][1]==='old2'&&$rows[1][2]==='user note','editing one field preserves untouched old fields');
    $user=$pdo->query('SELECT discord_username,locale FROM users WHERE id=1')->fetch(PDO::FETCH_NUM);$check($user===['old name','ja'],'migration name undone while later user locale retained');
    $query=$pdo->prepare('SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$query->execute(['users']);$check((int)$query->fetchColumn()>=201,'deleted later user ID high-water mark retained');$check($pdo->query("SHOW TABLES LIKE 'merge_added'")->fetchAll()===[],'unmodified newly migrated table removed');$check((int)$pdo->query('SELECT COUNT(*) FROM merge_links')->fetchColumn()===2,'composite keys and new child relation retained');
    // Reconstruct updated state and force a uniqueness conflict against the old state.
    $database->restore($current['path'],$current['metadata']);$recreated=$snapshot('recreated');$recreatedOutput=$directory.'/recreated-merged.jsonl';$recreatedMetadata=$merger->prepare($before,$baseline,$recreated,$recreatedOutput);$check($recreatedMetadata['rows']===$metadata['rows'],'equivalent restored schema with explicit inherited charset remains mergeable');
    $pdo->exec("UPDATE merge_items SET content='migration1',payload=NULL WHERE id=1");$pdo->exec("INSERT INTO merge_items VALUES(6,'old1',NULL,NULL)");$conflict=$snapshot('conflict');$reject(fn()=>$merger->prepare($before,$baseline,$conflict,$directory.'/conflict-merged.jsonl'),'UPDATE_DB_ROLLBACK_CONFLICT');$check($pdo->query("SELECT content FROM merge_items WHERE id=6")->fetchColumn()==='old1'&&!is_file($directory.'/conflict-merged.jsonl'),'constraint conflict rejected before live change and partial output removed');$pdo->exec('DELETE FROM merge_items WHERE id=6');
    $pdo->exec("UPDATE merge_added SET value='later user value' WHERE id=1");$changedTable=$snapshot('changed-table');$reject(fn()=>$merger->prepare($before,$baseline,$changedTable,$directory.'/changed-merged.jsonl'),'UPDATE_DB_ROLLBACK_CONFLICT');$check($pdo->query('SELECT value FROM merge_added WHERE id=1')->fetchColumn()==='later user value','user data in new-only table is never silently discarded');
    $pdo->exec("UPDATE merge_added SET value='migration seed' WHERE id=1");$pdo->exec('ALTER TABLE merge_items ADD COLUMN new_field TEXT NULL');$changedSchema=$snapshot('schema-current');$reject(fn()=>$merger->prepare($before,$baseline,$changedSchema,$directory.'/schema-merged.jsonl'),'UPDATE_DB_ROLLBACK_CONFLICT');$check($pdo->query("SHOW COLUMNS FROM merge_items LIKE 'new_field'")->fetchAll()!==[],'unexpected live schema change is never overwritten');
    $bad=$before;$bad['metadata']['sha256']=str_repeat('a',64);$reject(fn()=>$merger->prepare($bad,$baseline,$current,$directory.'/bad-merged.jsonl'),'INVALID_UPDATE_DB_BACKUP');$check(!is_file($directory.'/bad-merged.jsonl'),'corrupt snapshot never leaves a usable merge');
    echo "$count isolated DB rollback merge checks passed.\n";
}finally{
    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $table){if(!preg_match('/^[A-Za-z0-9_]+$/D',$table))throw new RuntimeException('Unexpected fixture table');$pdo->exec('DROP TABLE `'.$table.'`');}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');foreach(glob($directory.'/*') as $file)unlink($file);rmdir($directory);
}
