<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\{UpdateEngine,UpdateAccess,ReleasePackageBuilder,UpdatePackage};
use App\Database\{Database,Migrator};
use App\Http\HttpException;
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1'||!in_array(getenv('TEST_BACKUP_HOST'),['search-update-backup-mysql-20261004','search-update-backup-mariadb-20261004'],true))exit(1);
$directory=sys_get_temp_dir().'/update-engine-'.bin2hex(random_bytes(8));mkdir($directory,0700);$count=0;$root=dirname(__DIR__);$pdo=null;
$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
try{
    (new ReleasePackageBuilder())->build($root,$directory.'/base.tar');$initial=trim(file_get_contents($root.'/VERSION'));$live=$directory.'/live';(new UpdatePackage())->verify($directory.'/base.tar',$live,$initial,true);mkdir($live.'/storage',0700);
    $settings=require $root.'/config/config.example.php';$settings['installed']=true;$settings['database']=['host'=>getenv('TEST_BACKUP_HOST'),'port'=>3306,'name'=>'update_backup','user'=>'backup','password'=>getenv('TEST_BACKUP_PASSWORD')];$settings['session']=['name'=>'search_engine_test','secure'=>false];file_put_contents($live.'/config/config.php','<?php return '.var_export($settings,true).';');chmod($live.'/config/config.php',0600);file_put_contents($live.'/storage/user-upload.bin',"user\0bytes");file_put_contents($live.'/app/engine-old.php','<?php return true;');$configHash=hash_file('sha256',$live.'/config/config.php');
    $pdo=Database::connect($settings['database']);$check($pdo->query('SHOW TABLES')->fetchAll()===[],'engine uses dedicated empty schema');(new Migrator($pdo,$live.'/database/migrations'))->migrate();
    $pdo->prepare('INSERT INTO users(id,discord_id,discord_username,locale,created_at,updated_at) VALUES(?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([1,'999999999999999999','生成ユーザー','ja']);
    $pdo->prepare("UPDATE site_settings SET value_json=? WHERE setting_key='maintenance'")->execute(['true']);$signal=new App\Services\MaintenanceState($live.'/storage/runtime');$signal->synchronized(fn()=>$signal->publish(true));$signalHash=hash_file('sha256',$live.'/storage/runtime/maintenance.json');
    $databaseState=static function()use($pdo):array{
        $pdo->setAttribute(PDO::ATTR_STRINGIFY_FETCHES,true);$result=[];foreach($pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $name){if(!preg_match('/^[A-Za-z0-9_]+$/D',$name))throw new RuntimeException('Unexpected test table');$rows=$pdo->query('SELECT * FROM `'.$name.'`')->fetchAll(PDO::FETCH_NUM);$encoded=array_map(fn($row)=>json_encode(array_map(fn($cell)=>$cell===null?null:base64_encode($cell),$row),JSON_THROW_ON_ERROR),$rows);sort($encoded);$query=$pdo->prepare('SELECT COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY ORDINAL_POSITION');$query->execute([$name]);$result[$name]=[$query->fetchAll(PDO::FETCH_NUM),$encoded];}ksort($result);return $result;
    };
    $filesState=static function()use($live):array{$result=[];foreach(['app','public','lang','database','bin'] as $sub){$iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($live.'/'.$sub,FilesystemIterator::SKIP_DOTS));foreach($iterator as $file)if($file->isFile())$result[substr($file->getPathname(),strlen($live)+1)]=hash_file('sha256',$file->getPathname());}foreach(['VERSION','README.md','composer.json','config/config.example.php','config/providers.php'] as $path)$result[$path]=hash_file('sha256',$live.'/'.$path);ksort($result);return $result;};
    $protected=fn()=>hash_file('sha256',$live.'/config/config.php')===$configHash&&file_get_contents($live.'/storage/user-upload.bin')==="user\0bytes"&&hash_file('sha256',$live.'/storage/runtime/maintenance.json')===$signalHash;
    $open=static function()use($live):bool{$lease=(new UpdateAccess($live.'/storage/updates/access'))->enter();if($lease===null)return false;$lease->release();return true;};
    $source=$directory.'/candidate-source';(new UpdatePackage())->verify($directory.'/base.tar',$source,$initial,true);file_put_contents($source.'/VERSION','2.0.0');file_put_contents($source.'/app/engine-added.php','<?php return true;');
    file_put_contents($source.'/database/migrations/017_engine_fixture.php','<?php return new class {public function up(PDO $pdo):void{$pdo->exec("CREATE TABLE engine_added(id INT PRIMARY KEY) ENGINE=InnoDB");$pdo->prepare("UPDATE users SET discord_username=? WHERE id=?")->execute(["updated",1]);} public function down(PDO $pdo):void{$pdo->exec("DROP TABLE engine_added");}};');
    $package=static function(string $version,string $name)use($source,$directory):array{file_put_contents($source.'/VERSION',$version);$archive=$directory.'/'.$name.'.tar';(new ReleasePackageBuilder())->build($source,$archive);$manifest=(new UpdatePackage())->verify($archive,$directory.'/'.$name.'-stage',$version,true);return [$archive,$manifest];};
    [$archive,$manifest]=$package('2.0.0','good');$engine=new UpdateEngine($live);$oldDb=$databaseState();$oldFiles=$filesState();$state=$engine->apply($archive,$manifest);
    $check($state['job']['phase']==='complete'&&$state['backup']['from_version']===$initial&&trim(file_get_contents($live.'/VERSION'))==='2.0.0','complete update joins backup replace migration and real health');$check($pdo->query('SELECT discord_username FROM users WHERE id=1')->fetchColumn()==='updated'&&$pdo->query('SELECT COUNT(*) FROM migrations')->fetchColumn()==17,'new migration really changes schema and data');$check(!is_file($live.'/app/engine-old.php')&&is_file($live.'/app/engine-added.php')&&$protected()&&$open(),'managed file reconciliation preserves config upload and manual stop');
    $jobs=$live.'/storage/updates/jobs';$entries=array_values(array_diff(scandir($jobs),['.','..']));$check($entries===[$state['backup']['id']]&&array_values(array_diff(scandir($jobs.'/'.$entries[0]),['.','..']))===['database.jsonl','files.tar','manifest.json'],'only one physical backup generation retained');
    $retained=$state['backup']['id'];$currentDb=$databaseState();$currentFiles=$filesState();[$retainedArchive,$retainedManifest]=$package('2.1.0','retained-failure');$changed=0;$retainedEngine=new UpdateEngine($live,static function($event)use(&$changed){if($event==='file'&&++$changed===3)throw new RuntimeException('generated fault');});$failed=$retainedEngine->apply($retainedArchive,$retainedManifest);
    $check($failed['job']['phase']==='rolled_back'&&$failed['backup']['id']===$retained&&$databaseState()===$currentDb&&$filesState()===$currentFiles&&array_values(array_diff(scandir($jobs),['.','..']))===[$retained],'failed next update preserves previous successful physical generation');
    $state=$engine->rollback();$check($state['job']['phase']==='rolled_back'&&$state['backup']===null&&$databaseState()===$oldDb&&$filesState()===$oldFiles,'manual rollback after a failed attempt restores full previous files rows and schema');$check(array_values(array_diff(scandir($jobs),['.','..']))===[]&&$open()&&$protected(),'manual rollback consumes generation and reopens update access');
    $first=$engine->apply($archive,$manifest);[$thirdArchive,$thirdManifest]=$package('3.0.0','third');$next=$engine->apply($thirdArchive,$thirdManifest);$check($next['backup']['from_version']==='2.0.0'&&!is_dir($jobs.'/'.$first['backup']['id'])&&count(array_diff(scandir($jobs),['.','..']))===1,'later successful update retires older physical generation');$engine->rollback();
    $baselineDb=$databaseState();$baselineFiles=$filesState();[$faultArchive,$faultManifest]=$package('4.0.0','fault');chmod($live,0555);try{$state=(new UpdateEngine($live))->apply($faultArchive,$faultManifest);$check($state['job']['phase']==='failed'&&$state['job']['error']==='UPDATE_TARGET_NOT_WRITABLE'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles&&$open(),'readonly deployment rejects before mutation and safely reopens access');}finally{chmod($live,0700);}
    $changed=0;$faultEngine=new UpdateEngine($live,static function($event)use(&$changed){if($event==='file'&&++$changed===3)throw new RuntimeException('generated secret');});$state=$faultEngine->apply($faultArchive,$faultManifest);$check($state['job']['phase']==='rolled_back'&&$state['job']['error']==='UPDATE_APPLY_FAILED'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles,'real partial file replacement automatically restores files and DB');$check($open()&&$protected(),'successful automatic rollback reopens access and preserves private data');
    file_put_contents($source.'/database/migrations/018_engine_failure.php','<?php return new class {public function up(PDO $pdo):void{$pdo->exec("CREATE TABLE engine_partial(id INT PRIMARY KEY) ENGINE=InnoDB");$pdo->prepare("UPDATE users SET discord_username=? WHERE id=?")->execute(["partial",1]);throw new RuntimeException("generated secret");}};');[$ddlArchive,$ddlManifest]=$package('5.0.0','ddl');$state=(new UpdateEngine($live))->apply($ddlArchive,$ddlManifest);$check($state['job']['phase']==='rolled_back'&&$state['job']['error']==='UPDATE_MIGRATION_FAILED'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles,'DDL and row changes before migration exception automatically restored');unlink($source.'/database/migrations/018_engine_failure.php');
    $healthEngine=new UpdateEngine($live,static function($event)use($live){if($event==='checking')file_put_contents($live.'/app/Views/home.php','<?php throw new RuntimeException("generated secret");');});$state=$healthEngine->apply($faultArchive,$faultManifest);$check($state['job']['phase']==='rolled_back'&&$state['job']['error']==='UPDATE_HEALTH_FAILED'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles,'new-runtime health failure automatically restores both snapshots');
    $crash=$directory.'/crash.php';file_put_contents($crash,'<?php require '.var_export($root.'/app/autoload.php',true).';$manifest=json_decode(file_get_contents($argv[3]),true,16,JSON_THROW_ON_ERROR);(new App\\Services\\UpdateEngine($argv[1],static function($event){if($event==="checking")exit(7);}))->apply($argv[2],$manifest);');$input=$directory.'/manifest-input.json';file_put_contents($input,json_encode($faultManifest,JSON_THROW_ON_ERROR));$process=proc_open([PHP_BINARY,$crash,$live,$faultArchive,$input],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$output=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$check(proc_close($process)===7&&$output===''&&$error===''&&!$open(),'real process exit after migration leaves update stopped');$state=(new UpdateEngine($live))->recover();$check($state['job']['phase']==='rolled_back'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles&&$open(),'new engine instance recovers interrupted job from durable snapshots');
    $backupBytes=null;$backupPath=null;$changed=0;$brokenEngine=new UpdateEngine($live,static function($event,$job)use(&$backupBytes,&$backupPath,&$changed,$pdo){if($event==='file'&&++$changed===3){$backupPath=$job.'/files.tar';$backupBytes=file_get_contents($backupPath);$bad=$backupBytes;$bad[10]=$bad[10]==='x'?'y':'x';file_put_contents($backupPath,$bad);$pdo->prepare('UPDATE users SET discord_username=? WHERE id=?')->execute(['during-fault',1]);throw new RuntimeException('generated secret');}});
    try{$brokenEngine->apply($faultArchive,$faultManifest);throw new LogicException('Unexpected rollback');}catch(HttpException $error){$check($error->errorCode==='UPDATE_ROLLBACK_FAILED','corrupt file snapshot prevents false rollback success');}
    $check($brokenEngine->status()['job']['phase']==='rollback_failed'&&!$open()&&$databaseState()===$baselineDb,'DB still restored even when file rollback fails; access stays stopped');file_put_contents($backupPath,$backupBytes);$state=(new UpdateEngine($live))->recover();$check($state['job']['phase']==='rolled_back'&&$filesState()===$baselineFiles&&$databaseState()===$baselineDb&&$open()&&$protected(),'repaired snapshot supports retry of failed rollback');
    $manifestBytes=null;$manifestPath=null;$changed=0;$manifestEngine=new UpdateEngine($live,static function($event,$job)use(&$manifestBytes,&$manifestPath,&$changed){if($event==='file'&&++$changed===3){$manifestPath=$job.'/manifest.json';$manifestBytes=file_get_contents($manifestPath);file_put_contents($manifestPath,'corrupt manifest');throw new RuntimeException('generated secret');}});
    try{$manifestEngine->apply($faultArchive,$faultManifest);throw new LogicException('Unexpected manifest recovery');}catch(HttpException $error){$check($error->errorCode==='UPDATE_ROLLBACK_FAILED','journal manifest digest refuses corrupted rollback target list');}
    $check(!$open()&&$databaseState()===$baselineDb,'manifest corruption retains stop while still attempting DB restoration');file_put_contents($manifestPath,$manifestBytes);$state=(new UpdateEngine($live))->recover();$check($state['job']['phase']==='rolled_back'&&$databaseState()===$baselineDb&&$filesState()===$baselineFiles&&$open(),'restored manifest permits durable retry');
    $check(!str_contains(file_get_contents($live.'/storage/updates/journal/journal.json'),'generated secret'),'journal never stores exception text or fixture secret');
    echo "$count isolated update engine checks passed.\n";
}finally{
    if($pdo!==null){$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $name){if(!preg_match('/^[A-Za-z0-9_]+$/D',$name))throw new RuntimeException('Unexpected table');$pdo->exec('DROP TABLE `'.$name.'`');}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}
    $remove($directory);
}
