<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\{UpdateAccess,UpdateAccessPaused,UpdateAccessRestart,LogSchedule};
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1')exit(1);
$count=0;$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$root=dirname(__DIR__);$directory=sys_get_temp_dir().'/update-access-'.bin2hex(random_bytes(8));mkdir($directory,0700);$access=new UpdateAccess($directory.'/access');
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
$run=static function(array $command):array{$process=proc_open($command,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($process))throw new RuntimeException('Child process failed');fclose($pipes[0]);$output=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return [proc_close($process),$output,$error];};
try{
    $lease=$access->enter();$second=$access->enter();$check($lease!==null&&$second!==null,'concurrent ordinary leases allowed');$lease->release();$second->release();$check($access->generation()==='','initial generation empty');
    $result=$access->exclusive(function()use($access,$check){$check($access->enter()===null,'new access denied inside update');try{$access->exclusive(fn()=>null);throw new LogicException('Concurrent update allowed');}catch(UpdateAccessPaused){$check(true,'second updater rejected');}return 'complete';});$check($result==='complete'&&$access->enter()!==null,'successful operation reopens access');$generation=$access->generation();$check(strlen($generation)===32,'completed update advances code generation');
    try{$access->exclusive(fn()=>throw new RuntimeException('generated fault'));throw new LogicException('Failure hidden');}catch(RuntimeException $error){$check($error->getMessage()==='generated fault','operation failure propagated');}
    $check($access->enter()===null&&$access->generation()===$generation,'failed operation remains stopped without advancing generation');try{$access->exclusive(fn()=>null);throw new LogicException('Reopened failed update');}catch(UpdateAccessPaused){$check(true,'normal retry cannot erase failed update marker');}
    $access->exclusive(fn()=>null,recover:true);$check($access->enter()!==null&&$access->generation()!==$generation,'explicit recovery resumes only after successful callback');
    $lease=$access->enter();try{$access->exclusive(fn()=>throw new LogicException('Should not run'),timeout:1);throw new LogicException('Drain succeeded prematurely');}catch(UpdateAccessPaused){$check(true,'in-flight lease prevents mutation until drained');}$lease->release();$check($access->enter()===null,'drain timeout keeps update stopped');$access->exclusive(fn()=>null,recover:true);
    $autoload=$root.'/app/autoload.php';$child=$directory.'/reader.php';file_put_contents($child,'<?php require '.var_export($autoload,true).'; $lease=(new App\\Services\\UpdateAccess('.var_export($directory.'/access',true).'))->enter(); if($lease===null)exit(2); register_shutdown_function(function(){usleep(200000);file_put_contents('.var_export($directory.'/shutdown',true).',"done");}); file_put_contents('.var_export($directory.'/ready',true).',"ready"); usleep(400000);');
    $process=proc_open([PHP_BINARY,$child],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$deadline=microtime(true)+5;while(!is_file($directory.'/ready')){if(microtime(true)>$deadline)throw new RuntimeException('Reader not ready');usleep(10000);}
    $access->exclusive(function()use($directory,$check){$check(is_file($directory.'/shutdown'),'lease survives shutdown callback writes');});$output=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$check(proc_close($process)===0&&$output===''&&$error==='','real child request drained without errors');
    $crash=$directory.'/crash.php';file_put_contents($crash,'<?php require '.var_export($autoload,true).'; (new App\\Services\\UpdateAccess('.var_export($directory.'/access',true).'))->exclusive(function(){exit(7);});');[$exit]=$run([PHP_BINARY,$crash]);$check($exit===7&&$access->enter()===null,'process exit retains durable stop marker');$access->exclusive(fn()=>null,recover:true);
    foreach(['access.lock','operation.lock','pending','generation'] as $name){$target=$directory.'/other-'.$name;file_put_contents($target,'protected');$path=$directory.'/unsafe-'.$name;mkdir($path);symlink($target,$path.'/'.$name);$unsafe=new UpdateAccess($path);try{if($name==='access.lock')$unsafe->enter();elseif($name==='generation')$unsafe->generation();else $unsafe->exclusive(fn()=>null,recover:true);throw new LogicException('Unsafe link accepted');}catch(RuntimeException $error){$check($error->getMessage()==='UPDATE_ACCESS_UNAVAILABLE','link rejected '.$name);}$check(file_get_contents($target)==='protected','link target unchanged '.$name);}
    $events=[];$delays=[];$schedule=new LogSchedule();$schedule->run(fn()=>throw new UpdateAccessPaused(),function($event)use(&$events){$events[]=$event;},86400,3600,2,function($delay)use(&$delays){$delays[]=$delay;});$check(array_column($events,'status')===['paused','paused']&&$delays===[30],'paused maintenance retries without ordinary success or errors');$events=[];$exit=$schedule->run(fn()=>throw new UpdateAccessRestart(),function($event)use(&$events){$events[]=$event;},86400,3600,5);$check($exit===0&&count($events)===1&&$events[0]['status']==='restarting','generation change requests clean worker restart');
    $clone=$directory.'/worker';foreach(['app/Services','bin','storage/updates'] as $path)mkdir($clone.'/'.$path,0700,true);copy($root.'/app/autoload.php',$clone.'/app/autoload.php');foreach(['UpdateAccess','LogSchedule','LogMaintenance'] as $class)copy($root.'/app/Services/'.$class.'.php',$clone.'/app/Services/'.$class.'.php');foreach(['update-check-worker','log-maintenance','check-updates','cleanup-logs','cleanup-backgrounds','build-release','migrate','setup-key'] as $name)copy($root.'/bin/'.$name.'.php',$clone.'/bin/'.$name.'.php');
    $workerAccess=new UpdateAccess($clone.'/storage/updates/access');$workerAccess->exclusive(function()use($run,$clone,$check){
        foreach([['update-check-worker','--cycles=1'],['log-maintenance','--cycles=1']] as [$name,$option]){[$exit,$output,$error]=$run([PHP_BINARY,$clone.'/bin/'.$name.'.php',$option]);$event=json_decode(trim($output),true);$check($exit===0&&$error===''&&($event['status']??null)==='paused','worker pauses before loading nonexistent config/DB '.$name);}
        foreach(['check-updates','cleanup-logs','cleanup-backgrounds','build-release','migrate','setup-key'] as $name){[$exit,$output,$error]=$run([PHP_BINARY,$clone.'/bin/'.$name.'.php']);$check($exit===1&&$output===''&&$error!==''&&!str_contains($error,'Stack trace'),'one-shot CLI stops before config/DB '.$name);}
    });
    $check(!is_dir($clone.'/storage/logs')&&!is_dir($clone.'/storage/log-pending'),'paused CLI paths write no application logs');echo "$count update access checks passed.\n";
}finally{$remove($directory);}
