<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\{UpdateEngine,UpdateCommands,UpdateRunner,UpdatePackage,ReleasePackageBuilder,UpdateAccess};
use App\Repositories\{AdminRepository,UpdateHistoryRepository};
use App\Database\{Database,Migrator};
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1'||!in_array(getenv('TEST_BACKUP_HOST'),['search-update-backup-mysql-20261004','search-update-backup-mariadb-20261004'],true))exit(1);
$count=0;$root=dirname(__DIR__);$directory=sys_get_temp_dir().'/update-runner-'.bin2hex(random_bytes(8));mkdir($directory,0700);$pdo=null;$owned=false;
$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
try{
    (new ReleasePackageBuilder())->build($root,$directory.'/base.tar');$initial=trim(file_get_contents($root.'/VERSION'));$live=$directory.'/live';(new UpdatePackage())->verify($directory.'/base.tar',$live,$initial,true);mkdir($live.'/storage',0700);
    $settings=require $root.'/config/config.example.php';$settings['installed']=true;$settings['database']=['host'=>getenv('TEST_BACKUP_HOST'),'port'=>3306,'name'=>'update_backup','user'=>'backup','password'=>getenv('TEST_BACKUP_PASSWORD')];file_put_contents($live.'/config/config.php','<?php return '.var_export($settings,true).';');chmod($live.'/config/config.php',0600);
    $until=time()+60;do{try{$pdo=Database::connect($settings['database']);break;}catch(PDOException){if(time()>=$until)throw new RuntimeException('Dedicated runner DB unavailable');usleep(200000);}}while(true);
    $check($pdo->query('SHOW TABLES')->fetchAll()===[],'runner uses dedicated empty schema');$owned=true;(new Migrator($pdo,$live.'/database/migrations'))->migrate();
    $pdo->prepare('INSERT INTO users(id,discord_id,discord_username,locale,created_at,updated_at) VALUES(1,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['999999999999999998','Runner verification','en']);$pdo->exec('INSERT INTO administrators(user_id,created_at,updated_at) VALUES(1,UTC_TIMESTAMP(),UTC_TIMESTAMP())');
    $admin=new AdminRepository($pdo);$history=new UpdateHistoryRepository($pdo);$commands=new UpdateCommands($live.'/storage/updates/commands',fn($id)=>$admin->isAdministrator($id),fn($r,$e)=>$history->record($r,$e),fn($r)=>$history->matches($r));$engine=new UpdateEngine($live);
    $source=$directory.'/source';(new UpdatePackage())->verify($directory.'/base.tar',$source,$initial,true);file_put_contents($source.'/VERSION','2.0.0');(new ReleasePackageBuilder())->build($source,$directory.'/candidate.tar');$downloads=0;
    $prepare=static function($request,$archive,$stage)use($directory,&$downloads){++$downloads;copy($directory.'/candidate.tar',$archive);chmod($archive,0600);return (new UpdatePackage())->verify($archive,$stage,$request['to_version'],false);};$runner=new UpdateRunner($live,$commands,$engine,$prepare);
    $selection=['from_version'=>$initial,'to_version'=>'2.0.0','channel'=>'stable','repository'=>'choko1229/Search-StartPage','release_id'=>1];
    $process=proc_open([PHP_BINARY,$live.'/bin/run-update.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$check(proc_close($process)===0&&$err===''&&json_decode($out,true)===['format'=>1,'request_id'=>null,'status'=>'idle','error'=>null],'real CLI worker entry is idle in dedicated disposable deployment');
    $check($runner->run()['request']===null&&$downloads===0,'idle runner creates no pretend update');
    $state=$commands->enqueue(1,'apply',$selection,0);$applyId=$state['request']['id'];$state=$runner->run();
    $check($state['request']['status']==='complete'&&trim(file_get_contents($live.'/VERSION'))==='2.0.0'&&$downloads===1,'queued command executes real engine update');
    $check($engine->status()['job']['request_id']===$applyId&&$history->listing()[0]['status']==='complete','engine and DB outcome share exact request identity');
    $logs=(int)$pdo->query('SELECT COUNT(*) FROM log_entries')->fetchColumn();$runner->run();$check($downloads===1&&(int)$pdo->query('SELECT COUNT(*) FROM log_entries')->fetchColumn()===$logs,'terminal worker retry neither executes nor duplicates audit');
    $favoriteId='00000000-0000-4000-8000-000000000005';$pdo->prepare('INSERT INTO favorites(id,user_id,client_id,name,url,created_at,updated_at) VALUES(?,1,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([$favoriteId,$favoriteId,'After update','https://example.test/after']);
    $pdo->prepare('INSERT INTO sync_states(user_id,version,document,updated_at) VALUES(1,?,?,UTC_TIMESTAMP())')->execute([7,'{"preferences":{"theme":"glass"}}']);
    $keptIds=[];$failedRunner=new UpdateRunner($live,$commands,$engine,static function(){throw new App\Http\HttpException(502,'UPDATE_SOURCE_NOT_FOUND');});
    for($i=0;$i<25;$i++){$state=$commands->enqueue(1,'apply',array_replace($selection,['from_version'=>'2.0.0','to_version'=>'3.0.0']),$commands->status()['revision']);$keptIds[]=$state['request']['id'];$failedRunner->run();}
    $state=$commands->enqueue(1,'rollback',array_replace($selection,['from_version'=>'2.0.0','to_version'=>$initial,'release_id'=>null]),$commands->status()['revision']);$rollbackId=$state['request']['id'];$state=$runner->run();
    $check($state['request']['status']==='rolled_back'&&trim(file_get_contents($live.'/VERSION'))===$initial&&$downloads===1,'manual rollback command restores real prior generation without download');
    $rows=$history->listing(100);$mapped=array_column($rows,'status','request_id');$check(($mapped[$applyId]??null)==='complete'&&($mapped[$rollbackId]??null)==='rolled_back','DB rollback retains completed apply and rollback records');
    $check(count(array_intersect($keptIds,array_keys($mapped)))===25,'manual rollback retains audit history beyond the private twenty-entry list');
    $auditCount=0;$auditQuery=$pdo->prepare('SELECT COUNT(*) FROM log_entries WHERE event_id IN (?,?)');foreach($keptIds as $keptId){$auditQuery->execute([substr(hash('sha256',$keptId.':requested:queued'),0,32),substr(hash('sha256',$keptId.':finished:failed'),0,32)]);$auditCount+=(int)$auditQuery->fetchColumn();}
    $check($auditCount===50,'all twenty-five later acceptance and outcome audit pairs survive rollback');
    $errorIds=array_map(static fn($id)=>substr(hash('sha256',$id.':update-error:failed:UPDATE_SOURCE_NOT_FOUND'),0,32),$keptIds);
    $errorQuery=$pdo->prepare("SELECT COUNT(*) FROM log_entries WHERE type='update_error' AND error_code='UPDATE_SOURCE_NOT_FOUND' AND event_id IN (".implode(',',array_fill(0,count($errorIds),'?')).')');$errorQuery->execute($errorIds);$check((int)$errorQuery->fetchColumn()===25,'real worker errors remain separately classified after DB rollback');
    $outbox=new App\Services\AdminAuditLogger($pdo,new App\Services\FileLogger($live.'/storage/logs'));$outbox->flush();$outbox->flush();
    $errorLines=[];foreach(glob($live.'/storage/logs/*.jsonl')?:[] as $file)foreach(file($file,FILE_IGNORE_NEW_LINES) as $line){$entry=json_decode($line,true,flags:JSON_THROW_ON_ERROR);if($entry['level']==='update_error'&&in_array($entry['context']['change']['request_id']??null,$keptIds,true))$errorLines[]=$entry;}
    $check(count($errorLines)===25&&count(array_unique(array_column(array_column($errorLines,'context'),'audit_id')))===25,'real worker outcome errors are delivered once to files after rollback');
    $check($pdo->query('SELECT COUNT(*) FROM favorites')->fetchColumn()==1&&$pdo->query('SELECT version FROM sync_states WHERE user_id=1')->fetchColumn()==7&&$pdo->query('SELECT document FROM sync_states WHERE user_id=1')->fetchColumn()==='{"preferences":{"theme":"glass"}}','manual rollback preserves later favorites and cloud sync data');
    $query=$pdo->prepare('SELECT COUNT(*) FROM log_entries WHERE event_id IN (?,?)');$query->execute([substr(hash('sha256',$rollbackId.':requested:queued'),0,32),substr(hash('sha256',$rollbackId.':finished:rolled_back'),0,32)]);$check((int)$query->fetchColumn()===2,'rollback restores acceptance and outcome audit removed by DB snapshot');
    $state=$commands->enqueue(1,'apply',$selection,$commands->status()['revision']);$state=$commands->claim($state['revision']);$state=$runner->run();$check($state['request']['status']==='failed'&&$state['request']['error']==='UPDATE_INTERRUPTED'&&$downloads===1,'claim interrupted before engine start is not executed again');
    $state=$commands->enqueue(1,'apply',$selection,$commands->status()['revision']);$pdo->exec('UPDATE administrators SET admin_flag=0 WHERE user_id=1');try{$runner->run();throw new LogicException('Unexpected success');}catch(App\Http\HttpException $e){$check($e->errorCode==='FORBIDDEN'&&$downloads===1,'worker rechecks actual administrator before download');}$pdo->exec('UPDATE administrators SET admin_flag=1 WHERE user_id=1');
    $state=$commands->enqueue(1,'apply',$selection,$commands->status()['revision']);$bad=new UpdateRunner($live,$commands,$engine,static function(){throw new App\Http\HttpException(502,'UPDATE_SOURCE_NOT_FOUND');});$state=$bad->run();$check($state['request']['status']==='failed'&&$state['request']['error']==='UPDATE_SOURCE_NOT_FOUND'&&$downloads===1,'download failure produces fixed persisted outcome without execution');
    // Real process exit after migration, then a different worker resumes only the bound job.
    $prefixedSelection=array_replace($selection,['to_version'=>'v2.0.0']);
    $state=$commands->enqueue(1,'apply',$prefixedSelection,$commands->status()['revision']);$crashId=$state['request']['id'];$script=$directory.'/crash.php';
    file_put_contents($script,'<?php require '.var_export($root.'/app/autoload.php',true).';$root=$argv[1];$config=App\\Config::load($root);$pdo=App\\Database\\Database::connect($config->get("database"));$admin=new App\\Repositories\\AdminRepository($pdo);$history=new App\\Repositories\\UpdateHistoryRepository($pdo);$commands=new App\\Services\\UpdateCommands($root."/storage/updates/commands",fn($id)=>$admin->isAdministrator($id),fn($r,$e)=>$history->record($r,$e),fn($r)=>$history->matches($r));$engine=new App\\Services\\UpdateEngine($root,static function($event){if($event==="checking")exit(7);});$prepare=static function($r,$archive,$stage)use($argv){copy($argv[2],$archive);chmod($archive,0600);return (new App\\Services\\UpdatePackage())->verify($archive,$stage,$r["to_version"],false);};(new App\\Services\\UpdateRunner($root,$commands,$engine,$prepare))->run();');
    $process=proc_open([PHP_BINARY,$script,$live,$directory.'/candidate.tar'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$check(proc_close($process)===7&&$out===''&&$err===''&&$commands->status()['request']['status']==='running','real worker process exit retains running command and journal');
    $state=$runner->run();$check($state['request']['id']===$crashId&&$state['request']['status']==='rolled_back'&&trim(file_get_contents($live.'/VERSION'))===$initial&&$downloads===1,'fresh worker recovers bound interrupted update without downloading or executing it again');
    $check($history->listing()[0]['request_id']===$crashId&&$history->listing()[0]['status']==='rolled_back','recovered worker projects actual DB outcome');
    $check(array_diff(scandir($live.'/storage/updates/incoming'),['.','..'])===[],'incoming package and stage cleaned after interrupted recovery');
    $state=$commands->enqueue(1,'apply',$prefixedSelection,$commands->status()['revision']);$prefixedId=$state['request']['id'];$state=$runner->run();
    $check($state['request']['status']==='complete'&&$state['request']['to_version']==='v2.0.0'&&$engine->status()['job']['to_version']==='2.0.0'&&trim(file_get_contents($live.'/VERSION'))==='2.0.0','v-prefixed release completes with unchanged canonical package version');
    $check($history->listing()[0]['request_id']===$prefixedId&&$history->listing()[0]['status']==='complete','v-prefixed release projects complete outcome to real DB history');
    $state=$commands->enqueue(1,'rollback',array_replace($selection,['from_version'=>'2.0.0','to_version'=>$initial,'release_id'=>null]),$commands->status()['revision']);$state=$runner->run();
    $check($state['request']['status']==='rolled_back'&&trim(file_get_contents($live.'/VERSION'))===$initial,'v-prefixed release retains usable previous generation for rollback');
    $lease=(new UpdateAccess($live.'/storage/updates/access'))->enter();$check($lease!==null,'access reopened after worker recovery');$lease?->release();
    echo "$count isolated update runner checks passed.\n";
}finally{
    if($owned&&$pdo!==null){$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $name){if(!preg_match('/^[A-Za-z0-9_]+$/D',$name))throw new RuntimeException('Unexpected fixture table');$pdo->exec('DROP TABLE `'.$name.'`');}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}$remove($directory);
}
