<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1'||!in_array(getenv('TEST_BACKUP_HOST'),['search-update-backup-mysql-20261004','search-update-backup-mariadb-20261004'],true))exit(1);
$root=dirname(__DIR__);if(!is_file($root.'/storage/web-cache-test-only')||file_exists($root.'/config/config.php')||file_exists($root.'/live'))throw new RuntimeException('Fresh isolated UI deployment required');
$maria=getenv('TEST_BACKUP_HOST')==='search-update-backup-mariadb-20261004';
$settings=require $root.'/config/config.example.php';$settings['installed']=true;$settings['database']=['host'=>getenv('TEST_BACKUP_HOST'),'port'=>3306,'name'=>'update_backup','user'=>'backup','password'=>getenv('TEST_BACKUP_PASSWORD')];$settings['site']['url']=$maria?'http://update-mariadb.localhost:8108':'http://127.0.0.1:8107';$settings['session']=['name'=>$maria?'isolated_update_ui_maria':'isolated_update_ui','secure'=>false];$settings['updates']=['repository'=>'owner/repo','token'=>''];
$until=time()+60;do{try{$pdo=App\Database\Database::connect($settings['database']);break;}catch(PDOException){if(time()>=$until)throw new RuntimeException('Dedicated DB unavailable');usleep(100000);}}while(true);
if($pdo->query('SHOW TABLES')->fetchAll()!==[])throw new RuntimeException('Empty dedicated DB required');
$builder=new App\Services\ReleasePackageBuilder();$builder->build($root,$root.'/storage/ui-base.tar');$version=trim(file_get_contents($root.'/VERSION'));$live=$root.'/live';(new App\Services\UpdatePackage())->verify($root.'/storage/ui-base.tar',$live,$version,true);mkdir($live.'/storage',0700);file_put_contents($live.'/config/config.php','<?php return '.var_export($settings,true).';');chmod($live.'/config/config.php',0600);(new App\Database\Migrator($pdo,$live.'/database/migrations'))->migrate();
$auth=new App\Repositories\AuthRepository($pdo);$user=$auth->upsertIdentity(['id'=>'999999999999999979','username'=>'Generated isolated update admin','display_name'=>null,'avatar'=>null],'en');$pdo->prepare('INSERT INTO administrators(user_id,created_at,updated_at) VALUES (?,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([$user]);$device=bin2hex(random_bytes(16));$token=bin2hex(random_bytes(32));$auth->createDevice($user,$device,hash('sha256',$token),App\Auth\DeviceAgent::parse('Windows Chrome/120'),time());
file_put_contents($root.'/storage/ui-proof.json',json_encode(['version'=>$version,'configuration_sha256'=>hash_file('sha256',$live.'/config/config.php')],JSON_THROW_ON_ERROR));chmod($root.'/storage/ui-proof.json',0600);
mkdir($live.'/public/_test',0700);$login=$live.'/public/_test/ui-login.php';file_put_contents($login,'<?php setcookie("search_remember",'.var_export($device.'.'.$token,true).',["path"=>"/","httponly"=>true,"samesite"=>"Lax"]);header("Location: /admin/update",true,303);');chmod($login,0600);
$checks=new App\Services\UpdateChecks($live.'/storage/updates/checks',new App\Config($settings),$version,static fn()=>['status'=>200,'body'=>json_encode([['id'=>17,'tag_name'=>'2.0.0','draft'=>false,'prerelease'=>false,'published_at'=>'2026-10-01T00:00:00Z']])]);$checks->check('stable','',0);
$candidate=$root.'/storage/ui-candidate';(new App\Services\UpdatePackage())->verify($root.'/storage/ui-base.tar',$candidate,$version,true);file_put_contents($candidate.'/VERSION','2.0.0');file_put_contents($candidate.'/app/Views/admin-update.php',"\n<!-- generated-update-code-v2 -->\n",FILE_APPEND);$builder->build($candidate,$root.'/storage/ui-candidate.tar');
$entry=file_get_contents($live.'/bin/run-update.php');$start=strpos($entry,'$prepare=static');$end=strpos($entry,'$state=(new',$start);$fixture='$prepare=static function(array $request,string $archive,string $stage):array{copy('.var_export($root.'/storage/ui-candidate.tar',true).',$archive);return (new App\\Services\\UpdatePackage())->verify($archive,$stage,$request["to_version"],true);};';file_put_contents($live.'/bin/run-update.php',substr($entry,0,$start).$fixture.substr($entry,$end));
echo "Isolated UI deployment prepared; generated admin only; archive acquisition fixture.\n";
