<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/autoload.php';
use App\Services\UpdateJournal;
use App\Http\HttpException;
if(PHP_SAPI!=='cli'||getenv('SEARCH_TEST_MODE')!=='1')exit(1);
$count=0;$check=static function(bool $ok,string $name)use(&$count){if(!$ok)throw new RuntimeException($name);++$count;echo "PASS: $name\n";};
$root=dirname(__DIR__);$directory=sys_get_temp_dir().'/update-journal-'.bin2hex(random_bytes(8));mkdir($directory,0700);$clock=1000;$journal=new UpdateJournal($directory.'/state',static function()use(&$clock){return $clock;});
$remove=function($path)use(&$remove){if(is_dir($path)&&!is_link($path)){foreach(scandir($path) as $name)if($name!=='.'&&$name!=='..')$remove($path.'/'.$name);rmdir($path);}else unlink($path);};
$reject=static function(callable $action,string $code)use($check){try{$action();throw new LogicException('Unexpected success');}catch(HttpException $error){$check($error->errorCode===$code,$code);}};
$backup=static fn($version)=>['files'=>['version'=>$version,'files'=>7,'bytes'=>4096,'sha256'=>str_repeat('a',64)],'database'=>['bytes'=>500,'sha256'=>str_repeat('b',64),'database'=>str_repeat('c',64),'tables'=>2,'rows'=>3]];
$advance=static fn($state,$phase,$snapshot=null,$error=null)=>$journal->advance($state['job']['id'],$state['revision'],$phase,$snapshot,$error);
try{
    $state=$journal->status();$check($state['revision']===0&&$state['job']===null&&$state['backup']===null,'missing journal is initial state');$check(!is_file($directory.'/state/journal.json'),'status does not create pretend completed update');
    $state=$journal->start('1.0.0','2.0.0',0);$id=$state['job']['id'];$check($state['revision']===1&&$state['job']['phase']==='queued'&&strlen($id)===32,'new job queued with generated ID');$check((new UpdateJournal($directory.'/state'))->status()===$state,'new process object reads persisted job');$check((fileperms($directory.'/state/journal.json')&0777)===0600,'journal private permissions');
    $reject(fn()=>$journal->start('1.0.0','2.0.0',0),'UPDATE_STATE_CHANGED');$reject(fn()=>$journal->start('1.0.0','2.0.0',1),'UPDATE_IN_PROGRESS');$reject(fn()=>$advance($state,'complete'),'INVALID_UPDATE_TRANSITION');$check($journal->status()===$state,'invalid transition changes nothing');
    $state=$advance($state,'verified');$state=$advance($state,'backing_up');$reject(fn()=>$advance($state,'backed_up'),'INVALID_UPDATE_TRANSITION');$reject(fn()=>$advance($state,'backed_up',$backup('wrong-version')),'INVALID_UPDATE_BACKUP');$reject(fn()=>$advance($state,'failed',null,'generated secret marker'),'INVALID_UPDATE_TRANSITION');
    $state=$advance($state,'backed_up',$backup('1.0.0'));$check($state['backup']===null,'snapshot preparation never replaces completed rollback generation');
    $state=$advance($state,'replacing');$check($state['job']['backup']['files']['version']==='1.0.0','replace journal retains old backup metadata');$state=$advance($state,'migrating');$state=$advance($state,'checking');$state=$advance($state,'complete');$check($state['backup']['id']===$id&&$state['backup']['snapshot']===$backup('1.0.0'),'only health-complete job promotes rollback generation');
    $state=$journal->start('2.0.0','3.0.0',$state['revision']);$second=$state['job']['id'];$check($state['backup']['id']===$id&&count($state['history'])===1,'new attempt retains previous generation');$state=$advance($state,'verified');$state=$advance($state,'backing_up');$state=$advance($state,'backed_up',$backup('2.0.0'));$state=$advance($state,'replacing');$state=$advance($state,'rolling_back',null,'UPDATE_APPLY_FAILED');$state=$advance($state,'rollback_failed',null,'UPDATE_ROLLBACK_FAILED');$check($state['backup']['id']===$id&&$state['job']['phase']==='rollback_failed','failed rollback retains both snapshots and old generation metadata');$reject(fn()=>$journal->start('2.0.0','4.0.0',$state['revision']),'UPDATE_IN_PROGRESS');$state=$advance($state,'rolling_back');$state=$advance($state,'rolled_back');$check($state['backup']['id']===$id,'automatic rollback preserves earlier successful rollback generation');
    $state=$journal->start('2.0.0','4.0.0',$state['revision']);$newId=$state['job']['id'];foreach(['verified','backing_up','backed_up','replacing','migrating','checking','complete'] as $phase)$state=$advance($state,$phase,$phase==='backed_up'?$backup('2.0.0'):null);$check($state['backup']['id']===$newId&&$state['backup']['id']!==$id,'later success replaces sole generation pointer');$state=$advance($state,'rolling_back');$state=$advance($state,'rolled_back');$check($state['backup']===null,'manual rollback consumes current rollback generation');
    $clock=999;$state=$journal->start('2.0.0','5.0.0',$state['revision']);$clock=500;$state=$advance($state,'verified');$check($state['job']['updated_at']===$state['job']['created_at'],'backward clock never reverses job time');$state=$advance($state,'failed',null,'UPDATE_DOWNLOAD_FAILED');$clock=1200;
    $state=$journal->start('2.0.0','6.0.0',$state['revision']);foreach(['verified','backing_up','backed_up','replacing','migrating','checking','complete'] as $phase)$state=$advance($state,$phase,$phase==='backed_up'?$backup('2.0.0'):null);$retained=$state['backup']['id'];
    for($i=0;$i<25;$i++){$state=$journal->start('6.0.0','7.0.0',$state['revision']);$state=$advance($state,'failed',null,'UPDATE_DOWNLOAD_FAILED');}
    $check(count($state['history'])===20&&$state['backup']['id']===$retained&&in_array($retained,array_column($state['history'],'id'),true),'history bounded while retaining sole rollback owner across failures');
    $latestFailed=$state['job']['id'];$state=$journal->beginRollback($state['revision']);$check($state['job']['id']===$retained&&$state['job']['phase']==='rolling_back'&&in_array($latestFailed,array_column($state['history'],'id'),true),'manual rollback reactivates generation owner after failed attempts');$state=$advance($state,'rolled_back');$check($state['backup']===null,'reactivated manual rollback consumes sole generation');
    $state=$journal->start('6.0.0','8.0.0',$state['revision'],str_repeat('d',64));$check($state['job']['manifest_sha256']===str_repeat('d',64),'candidate manifest hash persists with job');$script=$directory.'/advance.php';file_put_contents($script,'<?php require '.var_export($root.'/app/autoload.php',true).';try{(new App\\Services\\UpdateJournal($argv[1]))->advance($argv[2],(int)$argv[3],"verified");echo "advanced";exit(0);}catch(App\\Http\\HttpException $e){echo $e->errorCode;exit(2);}');$children=[];
    for($i=0;$i<2;$i++){$process=proc_open([PHP_BINARY,$script,$directory.'/state',$state['job']['id'],(string)$state['revision']],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$children[]=[$process,$pipes];}
    $results=[];foreach($children as [$process,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$results[]=[proc_close($process),$out,$err];}sort($results);$check($results===[[0,'advanced',''],[2,'UPDATE_STATE_CHANGED','']],'two real concurrent processes permit exactly one transition');$state=$journal->status();$check($state['job']['phase']==='verified','winning transition survives process exit');$state=$advance($state,'failed',null,'UPDATE_INTERRUPTED');
    $path=$directory.'/state/journal.json';$original=file_get_contents($path);
    foreach(['{bad','{}','null',str_repeat('x',2097153)] as $json){file_put_contents($path,$json);$reject(fn()=>$journal->status(),'UPDATE_JOURNAL_INVALID');$check(file_get_contents($path)===$json,'corruption never silently reset');}file_put_contents($path,$original);
    foreach(['revision'=>-1,'format'=>3,'backup'=>null,'history'=>[['invalid'=>'value']]] as $key=>$value){$bad=$state;$bad[$key]=$value;if($key==='backup'){$bad['job']['phase']='complete';$bad['job']['error']=null;$bad['job']['backup']=$backup('6.0.0');}file_put_contents($path,json_encode($bad));$reject(fn()=>$journal->status(),'UPDATE_JOURNAL_INVALID');}file_put_contents($path,$original);
    unlink($path);symlink($directory.'/outside',$path);$reject(fn()=>$journal->status(),'UPDATE_JOURNAL_INVALID');unlink($path);file_put_contents($path,$original);$check(glob($directory.'/state/journal-*.tmp')===[],'no publication temp files remain');$check(!str_contains(file_get_contents($path),'generated secret marker'),'untrusted error text never persisted');
    echo "$count update journal checks passed.\n";
}finally{$remove($directory);}
